# Contexte

L'objectif de ce notebook est de proceder au pré-traitement des données suite à notre projet DPM portant sur l'étude de review issue du jeu de données de Tristpilot.   
Nous essaierons au cours du notebook de proposer une pipeline propre au traitement de langage naturel.

In [325]:
import pandas as pd

In [326]:
df = pd.read_csv('trustpilot_reviews_2005.csv')

In [327]:
df

,category,company,description,title,review,stars
0,Animals & Pets,ruffandtumbledogcoats.com,At Ruff and Tumble we are proud to be the mark...,Great quality dog drying robe although…,Great quality dog drying robe although had to ...,5
1,Animals & Pets,ruffandtumbledogcoats.com,At Ruff and Tumble we are proud to be the mark...,Really prompt service,"Really prompt service, The sofa covers have no...",5
2,Animals & Pets,ruffandtumbledogcoats.com,At Ruff and Tumble we are proud to be the mark...,Life saver,I’ve purchased first of those coats in May2020...,5
3,Animals & Pets,ruffandtumbledogcoats.com,At Ruff and Tumble we are proud to be the mark...,Brilliant coats,Brilliant coats. Really like the limited editi...,5
4,Animals & Pets,ruffandtumbledogcoats.com,At Ruff and Tumble we are proud to be the mark...,Great company and products,Great company and products. This is my 3rd dry...,5
...,...,...,...,...,...,...
123176,Media & Publishing,rarewaves.com,Rarewaves.com are one of the largest online re...,Still haven't received my purchase even…,Still haven't received my purchase even though...,1
123177,Media & Publishing,rarewaves.com,Rarewaves.com are one of the largest online re...,Ordered 10 days ago.....not a peep,Ordered 10 days ago thinking it would be here ...,1
123178,Media & Publishing,rarewaves.com,Rarewaves.com are one of the largest online re...,Bad first experience,Discs arrived broken and I still had to email ...,1
123179,Media & Publishing,rarewaves.com,Rarewaves.com are one of the largest online re...,Waiting .....2 mths now..never again,Waiting .....2 mths now..never again. No track...,1
123180,Media & Publishing,rarewaves.com,Rarewaves.com are one of the largest online re...,Avoid this company like the plague,Avoid this company like the plague. Also sell ...,1

In [384]:
# Afficher les catégories qui nous intéressent : ici Restaurant et Bars
df['category'].unique()

array(['Animals & Pets', 'Sports', 'Beauty & Well-being',
       'Hobbies & Crafts', 'Health & Medical', 'Shopping & Fashion',
       'Home & Garden', 'Electronics & Technology',
       'Food, Beverages & Tobacco', 'Home Services', 'Business Services',
       'Restaurants & Bars', 'Money & Insurance', 'Travel & Vacation',
       'Construction & Manufacturing', 'Utilities',
       'Vehicles & Transportation', 'Media & Publishing',
       'Public & Local Services', 'Education & Training',
       'Legal Services & Government', 'Events & Entertainment'],
      dtype=object)

In [385]:
#Création de notre jeu de données principal
df_resto = df[df['category'] == 'Restaurants & Bars']

# Pre-processing
Fonction dummy qui à pour but de supprimer les espaces

In [331]:
def dummy_word_split(texts):

    texts_out = []
    for text in texts:
        texts_out.append(text.split(" "))

    return texts_out

In [332]:
splitted_texts = dummy_word_split(df_resto['review'].tolist())

In [333]:
splitted_texts[0]

['Big',
 'up',
 'to',
 'my',
 'guy',
 'Moses',
 'who',
 'works',
 'in',
 'the',
 'itsu',
 'in',
 'Gatwick',
 'airport',
 'kind,gentle',
 'and',
 'welcoming',
 'and',
 'made',
 'my',
 'journey',
 'even',
 'better',
 'when',
 'him',
 'putting',
 'on',
 'a',
 'smile',
 'Thanks',
 'Moses',
 'continue',
 'to',
 'shine',
 'light',
 'on',
 'others',
 '🤞']

In [334]:
import itertools
from itertools import chain

def compute_word_occurence(texts):

    words = itertools.chain.from_iterable(texts)
    word_count = pd.Series(words).value_counts()
    word_count = pd.DataFrame({"Word": word_count.index, "Count": word_count.values})

    return word_count

In [335]:
compute_word_occurence(splitted_texts).head(20)

    Word  Count
0    the  13869
1    and  11515
2     to   9014
3      a   7521
4      I   6921
5    was   6372
6     of   4966
7    for   4112
8          3671
9     in   3239
10    it   2950
11    is   2718
12  with   2695
13   but   2491
14    my   2480
15  have   2442
16    on   2368
17   not   2348
18   had   2250
19   The   2218

# Obsevations 

Ici, nous observons que les mots les plus utilisés sont des stop-words : pronoms, déterminants, prépositions... Ces mots sont très nombreux et apportent peu d'information concernant les reviews : notre objectif premier sera des les supprimer.  
D'autres observations comme des répetitions dues aux majuscules : The/the, et des mots signifiant la même racine mais exprimer de manière différente : have/had, nous les traiterons plus bas.

In [386]:
#Qualité des données : les données contiennent-elles des string/Nan ?
import numpy as np

def quality(texts):

    assert all([isinstance(t,str) for t in texts]), "Présence de caractère non string"
    assert all([ t!= np.nan for t in texts]), "Présence de NaN"

    return True

In [337]:
def force_format(texts):
    return [str(t) for t in texts]

In [338]:
texts = force_format(df_resto['review'])

In [339]:
print(f" Si True pas de valeurs autres que String et pas de NaN, présence sinon\n {quality(texts)}")

 Si True pas de valeurs autres que String et pas de NaN, présence sinon
 True

Nos données ne comportent pas de caractère non string et pas de NaN

In [340]:
"""
import sys
!{sys.executable} -m pip install emoji

Importation de la librairie emoji afin de les supprimer dans les textes
"""

'\nimport sys\n!{sys.executable} -m pip install emoji\n\nImportation de la librairie emoji afin de les supprimer dans les textes\n'

In [341]:
#FOnction de suppression de balise/carractère spéciaux
import re
import emoji 

def filter_text(texts_in):
    
    texts_out = re.sub(r'https?:\/\/[A-Za-z0-9_.-~\-]*', ' ', texts_in, flags=re.MULTILINE)
    texts_out = re.sub(r'[(){}\[\]<>]', ' ', texts_out, flags=re.MULTILINE)
    texts_out = re.sub(r'&amp;#.*;', ' ', texts_out, flags=re.MULTILINE)
    texts_out = re.sub(r'&gt;', ' ', texts_out, flags=re.MULTILINE)
    texts_out = re.sub(r'â€™', "'", texts_out, flags=re.MULTILINE)
    texts_out = re.sub(r'\s+', ' ', texts_out, flags=re.MULTILINE)
    texts_out = re.sub(r'&#x200B;', ' ', texts_out, flags=re.MULTILINE)
    texts_out = re.sub(r"\(?\d{3}\D{0,3}\d{3}\D{0,3}\d{4}", '', texts_out, flags=re.MULTILINE)
    texts_out = emoji.replace_emoji(texts_out, replace='')
    texts_out = texts_out.lower()

    return texts_out

Nous avons observés plus haut la présence d'emojis qui n'apportent pas d'information dans le traitement de texte, bien que le jeu
de données semble correct aux niveaux des balises, cette méthode est généralement utilsée afin de supprimer des carractères non souhaités avec des Regex.  

Nous mettons nos carractères en minuscule afin de palier vu lors de la première phase.

In [342]:
texts = [filter_text(t) for t in texts]

In [343]:
texts

['big up to my guy moses who works in the itsu in gatwick airport kind,gentle and welcoming and made my journey even better when him putting on a smile thanks moses continue to shine light on others ',
 'great experience at itsu thanks to hospitality of moses at gatwick airport south terminal',
 'as itsu virgins we enjoyed a lovely first time experience at the itsu liverpool street. the staff were exceptionally good at helping us navigate our way through the ordering process, the food was hot, tasty and efficiently produced. we’ll certainly try itsu again!',
 'itsu at brunswick centre, camden is an extremely nice sushi place. the staff are very helpful especially ornella and wojciech who have taught me how to operate the technology. now i can scan with my app and claim my butterflies with ease. i have also been taught how to access my nhs discount. thank goodness for lovely staff who enjoy their jobs and make customers feel special.',
 'at itsu reading gate and clean restaurant and friendly staff. food was quick and great too! ',
 'my 13 year old son loves this restaurant chain. he ordered a rice box and absolutely loved it. he normally complains about eating vegetables but the way its cooked and presented meant he was happy to eat the veg. the decor is beautiful. ',
 'i ate at the itsu restaurant in brunswick centre. naast de excellent food the service was extra special. all smiles and genuine interest in us as tourists visiting for the first time. quick, efficient and friendly!',
 'excellent service, lovely food,i can highly recommend it.',
 'itsu has such a great menu with really fair prices. the sushi is phenomenal and always so fresh! i also love that it is a healthier option than most fast-food chains/restaurants. the atmosphere inside to dine in is always great too.  the only criticism i have is including the mini soy sauce bottle with every sushi pack - it’s quite wasteful as it may not be used. i think instead there should be an option to take a mini bottle of it if wanted. other than this the packaging is great : apart from this small criticism, everything else is perfect and i absolutely love the app with the loyalty scheme! would definitely recommend this amazing restaurant to everyone   ',
 "i have been visiting the brixton branch since it's opening just over a year ago and enjoy the convenience of grabbing a hot meal less than 5mins away from my office. i especially love the poached egg add-on and each dish i order tends to have that top up. i would highly recommend if you fancy some asian-inspired eat-in or takeaway fast food. only thing to bear in mind is that it's cashless eatery so old schoolers like myself have to whip out the card...",
 'this morning around 9:30 i visited itsu in euston station and they had issues with the card machine transactions and guess what, i got my lunch for free, i was really touched, thank you itsu, i hope your issues got solved and i appreciate your kindness! thank you!',
 'hi everyone, i work in bank, and quite often, for office lunches i go to itsu in cheapside.we are about 30 people in the office, and after collecting the orders from my work colleagues i forward my lunch list to renata, the shop manager.she is amazing, quick and well organized, but what counts the most, she is always smiling and make customers feels always very welcome.my experience at this itsu is absolutely positive, i do not know about the other itsu branches, i only know that every business should have someone like renata, and its success would be guaranteed !!!!dani',
 'i was struggling to redeem a voucher and approached the till. the manager came out to help me. i am a regular customer at the nhg branch and this woman is fantastic - always smiling, cheerful and extremely helpful. she promotes new products, helps customers and is very efficient. ',
 'the manager silverio at victoria station itsu was so kind and thoughtful on a day i felt unwell, offering me their fabulous chicken noodle soup, i’ll be heading back again soon. he made my day with a moment and gesture of kindness, thank you. ',
 'i find itsu on the kings road, chelsea very welcoming and really tasty food at a reasonable price. my favourite is the thai noodles which are priced just under seven pounds. where else can you find such a scrumptious dish for this price. i am handicapped on a mobility scooter yet the staff and manager adrian are so gracious and always help by giving me table service. they never object to my scooter being in the way.it is a pleasure to go to itsu on the kings rd, chelsea my last visit was on 23 february 2024. we are so lucky to have itsu locally. ',
 'my brother and i visited itsu victoria station yesterday. we were absolutely starving and exhausted, so we grabbed some gyoza and mochi. we were served by priya, who was friendly, smiling and extremely helpful, and she gave us a box of bao buns for free as it was the end of the day! a lovely extra at the end of a long day, so thank you priya!',
 "i love the food. it's tasty, well-presented, and a decent portion. the packaging is nicely done as well. ordering food using delivery services leaves food vulnerable to tampering not to mention arriving cold. not only does itsu's packaging keep food warm, it seals the food to prevent both spills and tampering.",
 'itsu victoria station is fabulous. the staff are great. the manager went over and beyond to cater for my tolerences. whenever i visit we are welcomed with a huge smile and cheerful attitude from the manager. i will always visit when int he area. thank you! ',
 'i visited itsu wembley park today and was surprised by how friendly the staff were, particularly gabriel. in addition to the great service food was also good, healthy and reasonably priced. cannot fault it at all.overall the visit made my day : ',
 'always clean and tidy. fast and friendly service and plenty of condiments, cutlery options and napkins available. we never feel rushed off our table when we’ve finished. ',
 'very good service and very nice people highly recommend ',
 "early adopter. i've been using itsu since it started and i'm still a fan. the salmon went through a very iffy phase for about 6 months crunchy texture,really not good but that was a couple of years ago , all good since. there is a difference between outlets, whether that's good or bad is subjective.*** itsu social media person ***please don't comment, i have no issue to be addressed and i don't need my ego stroked .no disrespect intended.",
 'i was disappointed when i bought sushi and realised it already had wasabi on it. unfortunately i do not like this so it was a waste of my money. i simply enquired online whether it was possible in the future to get this removed. sandra then went above and beyond and very kindly sent me some vouchers! i am impressed with their customer service and look forward to ordering sushi without wasabi in the future : ',
 "i buy my lunch from itsu fairly regularly. it's healthy and nutritious and minimal fuss. the shop near chancery lane, london is small, friendly and it's never busy because everyone else appears to go to wasabi!!the only reason this review doesn't have five stars is because they've recently stopped selling the rice and veggie dumplings! it was something that i would eat with a miso...i've had to explore other options which may have meant i've tried more food that they sell - but nothing really beats the ease and taste of the rice and dumplings...bring it back!!!!",
 'i previously gave itsu a low rating, but after visiting a couple of times after, i can say that it has improved vastly. the prices are still on the expensive side but the customer service is so much better. thank you',
 'itsu is a great sushi for its price. one can eat well for a budget price if sushi is on your lunch break. it’s quick, fresh, variety is good and eating facility is good. i have had better sushi at a high end restaurant. but then the cost includes expensive drinks, personal servers and top end sushi chefs. for a quick sushi on the go, itsu is very decent and good value.',
 'regular lunch of the chicken teryaki bowl at the soho branch. always good, tasty and quick, pleasant service',
 'good service, good food, nice to see more tasty healthy food options. maybe get rid of some of the sugary drinks on the shelves or make them smaller?! fish is v.g.',
 'average sushi but great customer experience. good if you are in a hurry!',
 'it was really good. no queue friendly staff and food to the ready. ',
 'i like some of the food dishes and the jasmine tea and consider it good value for money.i have been put off at a couple of locations by the excessively loud music being played. turn the volume down, please.',
 "i have used the just opened exeter branch of itsu 3 times in the last 10 or so days. ive done bullet points to simplify my thoughts.•fitted out the premises beautifully•the food is beautiful if not sometimes exactly what's described in the menu,put down to maybe more training or lack of experience.•does not accept cash.!!! this is legal tender & no company should take it on themselves to ban it. this particular one urks me.• no display of opening times on shop front.•funny closing times,8pm mon to thursday 9pm friday onwards, seems like your missing customers as the city has very little in the way of takeaway,least of all healthy alternatives.my review will be adjusted as & when things i am sure will improve. but the cash ban leaves me not recommending at this times as i am a strong advocate for the use of cash.",
 'great sushi, good service, always consistent, but really fed-up with their ridiculous attitude when requesting some ginger. every other boxed sushi vendor places some ginger in their offerings but itsu stopped doing this a while back. so i ask for a little ginger at the counter. having been assured - in writing - by itsu that their policy is to provide one packet of ginger free-of-charge per boxed item when requested at the till this is never realised and every time we have to go through a merry dance to not add a ridiculously trivial 5p for a sachet. this is not about the money: it is the inconsistency and childishness that is the frustration.',
 "not the worst place to work, job security is there although bad hours of work and not much reliability there, could have 15 hours a week, could have 45, depends. staff and management usually are god awful and people are promoted on nepotism basis while hr is quite alright and ceo isn't abandoning care for his employees, noone got left behind during covid while pret a manger fired like 40% of their staff",
 "i bought itsu crispy seaweed thins from a supermarket. my husband and i absolutely love them but i don't want to buy them again because the amount of plastic packaging used is horrendous! the individual packets contain plastic holders, wrapped in plastic, which are wrapped again in the outer layer of plastic keeping them together. each individual packet also contains a small plastic packet of a substance which stops the product from spoiling. i appreciate that the product is very delicate but, seriously, there has to be a more environmentally friendly way of delivering this product to customers. i just can't bear to throw packet after packet into the bin. please address this issue.",
 'i got myself the lloyds bank world elite card and it invited me to sign up to itsu as part of its rewards partners. i decided that i would give itsu a go and so i went into baths store to get some gyoza. firstly i couldn\'t use the app and it kept saying it wouldn\'t scan. i then couldn\'t get it to work. i ordered and went to the counter and said "are you able to add my butterflies onto my account" felt weird to say that! - only to be told that they couldn\'t because i needed to spend over a fiver... i explained that i had as it was £5.95 and i was told to go onto the website and there will be help on there. nope... no help whatsoever. not even an option to be able to ask for general question help. i decided to message marketing and upload the photo of the food and my receipt... nope. crashed and said there was an issue! not great service! ',
 'i looked up the menu online and it looked delicious. well presented in a bowl. even on the day of ordering it showed the dish in a bowl. then after ordering they gave it me in a cardboard tub. i thought the watery slop with flavoured water was overpriced for over £8.00.',
 'the food was okay, nothing special. but what annoyed me was that i ordered an english breakfast tea - in london - only to find they provided no milk of any sort. that is simply sloppy. i tried to drink it black, but it was so disgusting i could not do that.',
 'nothing special to be honest. i don’t support companies that charge 20% to sit down to eat so customers pay their tax. that’s just not on. i know a lot of companies so it. the rule apparently does not apply to hot food is what i was told. such i and other items apply he sushi is pretty good and fresh. i’m not sure about ingredients. particularly on their sauces because most companies that sell this sort of food use msg which is a particularly nasty ingredient. when i asked staff they told me they did not know about msg and to look at web site. yo sushi is as more informed and checked and told me some products like their soup contain it. i’m surprised of the lack of training at itsu. particularly because of the ordeal at pret and people with allergies. as a consequence, customers are always asked about whether they have an allergy. also, sulfites is another thing i don’t like whether you have an allergy or not. wagamama put it in their sauces as a preservative. to summarise, do your research on what they use, particularly soups and sauces. you might just be surprised that a place you eat regularly is causing you problems long term and using ingredients that are not good for you. don’t be mislead by the fact things like sushi are considered good for you. that might be the case but look out for what they add to all dishes i am going to update my review soon with an update concerning msg and sulfites',
 'my question is how can you have two different price for the vegetable dumplings! if it is hot it is priced at £3.49. if you have it cold it is £4.19.it makes no sense.',
 'thier always dirty , they don’t clean or sanitise most of thier counter tops and the trays that we use to eat food on. they’re always a fly hovering around and some of the staff are rude and overbearing, the suchi is always falling apart and can’t be picked up by the chop sticks , the dumplings in the miso soup is always falling apart and makes the soup look uninviting.  it puts me off eating there to be honest . thier toilets aren’t always clean and both men and women have to share the same toilet  it’s odd putting to say the least . ',
 'i have gotten the chicken and teriyaki rice bowl from here before and other foods as-well, but the most recent time i have gotten the chicken teriyaki rice bowl it gave me food poisoning! i remember looking at the chicken and thinking it looked funny but just ignored it as i had eaten it before. the worst food poisoning i have ever had. hot hot fever with the chills',
 "i went itsu eat beautiful at fosse park leicester last week for the first time customer service here not welcoming enough for me to return no smile & not at all welcoming so i very begrudgingly wanted to spend my money there.... anyway i did.... and so i opted for the salmon salad box promotional offer which looked good similar to the photo but unfortunately it seemed stingy for £6.99! very small piece of salmon cheap brown rice and some beans and other stuff in there it just tasted bland no flavour even with the dip that comes with it and it was just boring and definitely lacked flavour i wouldn't come back again as a greggs sandwich next door has more flavour! ",
 'i feel like the menu just got more boring, cheaper in terms of quality and less tasty. also a lot of the ingredients are really hard to digest. like why combine uncooked cabbages, kale, onions, etc all in one dish. why? who designs these menus? i feel bloated every time i go to itsu… it also got a lot more expensive as well and the whole menu feels tired and same, same. the app finally got a bit better but it’s still often buggy and the interface and how to get your freebies is not intuitive. i need a member of staff every time to trouble shoot… it used to be my favourite lunch spot but now i only go there if i forgot to bring in my lunch. and only because it’s the closest to the office.',
 'just tried itsu products from a supermarket for the first time. the teriyaki chicken bao buns had about 3mm of filling. all i could taste was bun. the pork gyoza had filling but not much flavour. the only reason i gave this review a 2 and not a 1 was the stuffed green and chile pancakes were reasonable enough filling and flavour.my daughter mentioned she generally liked itsu products so i gave her the rest out the freezer. next day she told me the bao buns had a ridiculously small amount of filling which was unusual. is this a factory error or just another company cutting their ingredients to rip off the customer?',
 'food was okay pretty good rather than very good, and rather overpriced but once again the app didn’t work. told the restaurant manager - nothing he could do and no way to add “credits” later. if you’re going to launch a loyalty scheme then you really should do it right or else it becomes an anti-loyalty scheme.',
 "i used to love going to itsu to the point where i would go there for most of my work lunch breaks. however, recently, when ordering my go-to avocado & sushi salmon set, i noticed a pea-sized dot of wasabi tucked underneath the sushi salmon, which tastes extremely unpleasant. there should be an option, like in most sushi restaurants to have wasabi 'on the side', rather than inside the sushi. there doesn't seem to be an option of avocado & salmon sushi without wasabi inside of the roll, so i'm very disappointed.",
 "for the price of their sushi, i am getting tired of the endless, undercooked, slightly crunchy and wet sushi rice not normal mirin moisture, just over-wet and soggy . if they want to keep their customers they need to get this most basic ingredient correctly prepared. it makes me feel ill.also, they need to find a way of using less disposable plastic. all in all i'm losing my will to eat there anymore. hanover square branch ",
 'itsu at stansted airport.i tried to pay in cash and found out that itsu is ‘cashless’. that’s a mild annoyance but i can live with it. what wasn’t okay is that the cash register display said ‘card preferred’ so when i pointed this out, the somewhat obnoxious itsu employee pointed out to a tiny little label which said ‘card only’ on the card machine. if you are going to go cashless, at least make it clear so that customers have a choice before being asked to pay. nobody likes to be told their cash is worthless. oh, and your sushi rice was undercooked on two occasions.',
 'poor experience at the new reading gate location. some of the food was under cooked and the dumplings were rubbery and cold in the centre. as for the service, glum faces and for the second visit in a row, the staff were slamming the self surface bin doors as they emptied them.it’s a shame as we had high hopes, but all three of us at our table agreed the food was under prepared and over priced. not sure we will be going back. at least not until we hear it’s improved. let’s hope these are the teething problems of a new branch. but after reading other reviews here, i wonder whether itsu has wider issues across its network.',

## Unification du texte & conversion des phrase en liste de mot

Spécialement prévu pour notre projet de Topic Modeling : nous ne souhaitons pas savoir si un mot se situe au début ou à la fin d'une phrase. Nous avons déjà supprimé les majuscules, nous procédons plus bas à la suppression des accents (bien que peut présent dans la langue anglaise).

In [344]:
"""
import sys
!{sys.executable} -m pip install tqdm
"""

'\nimport sys\n!{sys.executable} -m pip install tqdm\n'

In [345]:
"""
import sys
!{sys.executable} -m pip install gensim
"""

'\nimport sys\n!{sys.executable} -m pip install gensim\n'

In [346]:
from tqdm import tqdm
from gensim.utils import simple_preprocess

def sent_to_words(sentences):
    for sentence in tqdm(sentences):
        yield simple_preprocess(str(sentence), deacc=True)

In [347]:
texts = list(sent_to_words(texts))

100%|██████████| 5204/5204 [00:00<00:00, 8351.21it/s]

In [348]:
texts

[['big',
  'up',
  'to',
  'my',
  'guy',
  'moses',
  'who',
  'works',
  'in',
  'the',
  'itsu',
  'in',
  'gatwick',
  'airport',
  'kind',
  'gentle',
  'and',
  'welcoming',
  'and',
  'made',
  'my',
  'journey',
  'even',
  'better',
  'when',
  'him',
  'putting',
  'on',
  'smile',
  'thanks',
  'moses',
  'continue',
  'to',
  'shine',
  'light',
  'on',
  'others'],
 ['great',
  'experience',
  'at',
  'itsu',
  'thanks',
  'to',
  'hospitality',
  'of',
  'moses',
  'at',
  'gatwick',
  'airport',
  'south',
  'terminal'],
 ['as',
  'itsu',
  'virgins',
  'we',
  'enjoyed',
  'lovely',
  'first',
  'time',
  'experience',
  'at',
  'the',
  'itsu',
  'liverpool',
  'street',
  'the',
  'staff',
  'were',
  'exceptionally',
  'good',
  'at',
  'helping',
  'us',
  'navigate',
  'our',
  'way',
  'through',
  'the',
  'ordering',
  'process',
  'the',
  'food',
  'was',
  'hot',
  'tasty',
  'and',
  'efficiently',
  'produced',
  'we',
  'll',
  'certainly',
  'try',
  'itsu',
  'again'],
 ['itsu',
  'at',
  'brunswick',
  'centre',
  'camden',
  'is',
  'an',
  'extremely',
  'nice',
  'sushi',
  'place',
  'the',
  'staff',
  'are',
  'very',
  'helpful',
  'especially',
  'ornella',
  'and',
  'wojciech',
  'who',
  'have',
  'taught',
  'me',
  'how',
  'to',
  'operate',
  'the',
  'technology',
  'now',
  'can',
  'scan',
  'with',
  'my',
  'app',
  'and',
  'claim',
  'my',
  'butterflies',
  'with',
  'ease',
  'have',
  'also',
  'been',
  'taught',
  'how',
  'to',
  'access',
  'my',
  'nhs',
  'discount',
  'thank',
  'goodness',
  'for',
  'lovely',
  'staff',
  'who',
  'enjoy',
  'their',
  'jobs',
  'and',
  'make',
  'customers',
  'feel',
  'special'],
 ['at',
  'itsu',
  'reading',
  'gate',
  'and',
  'clean',
  'restaurant',
  'and',
  'friendly',
  'staff',
  'food',
  'was',
  'quick',
  'and',
  'great',
  'too'],
 ['my',
  'year',
  'old',
  'son',
  'loves',
  'this',
  'restaurant',
  'chain',
  'he',
  'ordered',
  'rice',
  'box',
  'and',
  'absolutely',
  'loved',
  'it',
  'he',
  'normally',
  'complains',
  'about',
  'eating',
  'vegetables',
  'but',
  'the',
  'way',
  'its',
  'cooked',
  'and',
  'presented',
  'meant',
  'he',
  'was',
  'happy',
  'to',
  'eat',
  'the',
  'veg',
  'the',
  'decor',
  'is',
  'beautiful'],
 ['ate',
  'at',
  'the',
  'itsu',
  'restaurant',
  'in',
  'brunswick',
  'centre',
  'naast',
  'de',
  'excellent',
  'food',
  'the',
  'service',
  'was',
  'extra',
  'special',
  'all',
  'smiles',
  'and',
  'genuine',
  'interest',
  'in',
  'us',
  'as',
  'tourists',
  'visiting',
  'for',
  'the',
  'first',
  'time',
  'quick',
  'efficient',
  'and',
  'friendly'],
 ['excellent',
  'service',
  'lovely',
  'food',
  'can',
  'highly',
  'recommend',
  'it'],
 ['itsu',
  'has',
  'such',
  'great',
  'menu',
  'with',
  'really',
  'fair',
  'prices',
  'the',
  'sushi',
  'is',
  'phenomenal',
  'and',
  'always',
  'so',
  'fresh',
  'also',
  'love',
  'that',
  'it',
  'is',
  'healthier',
  'option',
  'than',
  'most',
  'fast',
  'food',
  'chains',
  'restaurants',
  'the',
  'atmosphere',
  'inside',
  'to',
  'dine',
  'in',
  'is',
  'always',
  'great',
  'too',
  'the',
  'only',
  'criticism',
  'have',
  'is',
  'including',
  'the',
  'mini',
  'soy',
  'sauce',
  'bottle',
  'with',
  'every',
  'sushi',
  'pack',
  'it',
  'quite',
  'wasteful',
  'as',
  'it',
  'may',
  'not',
  'be',
  'used',
  'think',
  'instead',
  'there',
  'should',
  'be',
  'an',
  'option',
  'to',
  'take',
  'mini',
  'bottle',
  'of',
  'it',
  'if',
  'wanted',
  'other',
  'than',
  'this',
  'the',
  'packaging',
  'is',
  'great',
  'apart',
  'from',
  'this',
  'small',
  'criticism',
  'everything',
  'else',
  'is',
  'perfect',
  'and',
  'absolutely',
  'love',
  'the',
  'app',
  'with',
  'the',
  'loyalty',
  'scheme',
  'would',
  'definitely',
  'recommend',
  'this',
  'amazing',
  'restaurant',
  'to',
  'everyone'],
 ['have',
  'been',
  'visiting',
  'the',
  'brixton',
  'branch',
  'since',
  'it',
  'opening',
  'just',
  'over',
  'year',
  'ago',
  'and',
  'enjoy',
  'the',
  'convenience',
  'of',
  'grabbing',
  'hot',
  'meal',
  'less',
  'than',
  'mins',
  'away',
  'from',
  'my',
  'office',
  'especially',
  'love',
  'the',
  'poached',
  'egg',
  'add',
  'on',
  'and',
  'each',
  'dish',
  'order',
  'tends',
  'to',
  'have',
  'that',
  'top',
  'up',
  'would',
  'highly',
  'recommend',
  'if',
  'you',
  'fancy',
  'some',
  'asian',
  'inspired',
  'eat',
  'in',
  'or',
  'takeaway',
  'fast',
  'food',
  'only',
  'thing',
  'to',
  'bear',
  'in',
  'mind',
  'is',
  'that',
  'it',
  'cashless',
  'eatery',
  'so',
  'old',
  'schoolers',
  'like',
  'myself',
  'have',
  'to',
  'whip',
  'out',
  'the',
  'card'],
 ['this',
  'morning',
  'around',
  'visited',
  'itsu',
  'in',
  'euston',
  'station',
  'and',
  'they',
  'had',
  'issues',
  'with',
  'the',
  'card',
  'machine',
  'transactions',
  'and',
  'guess',
  'what',
  'got',
  'my',
  'lunch',
  'for',
  'free',
  'was',
  'really',
  'touched',
  'thank',
  'you',
  'itsu',
  'hope',
  'your',
  'issues',
  'got',
  'solved',
  'and',
  'appreciate',
  'your',
  'kindness',
  'thank',
  'you'],
 ['hi',
  'everyone',
  'work',
  'in',
  'bank',
  'and',
  'quite',
  'often',
  'for',
  'office',
  'lunches',
  'go',
  'to',
  'itsu',
  'in',
  'cheapside',
  'we',
  'are',
  'about',
  'people',
  'in',
  'the',
  'office',
  'and',
  'after',
  'collecting',
  'the',
  'orders',
  'from',
  'my',
  'work',
  'colleagues',
  'forward',
  'my',
  'lunch',
  'list',
  'to',
  'renata',
  'the',
  'shop',
  'manager',
  'she',
  'is',
  'amazing',
  'quick',
  'and',
  'well',
  'organized',
  'but',
  'what',
  'counts',
  'the',
  'most',
  'she',
  'is',
  'always',
  'smiling',
  'and',
  'make',
  'customers',
  'feels',
  'always',
  'very',
  'welcome',
  'my',
  'experience',
  'at',
  'this',
  'itsu',
  'is',
  'absolutely',
  'positive',
  'do',
  'not',
  'know',
  'about',
  'the',
  'other',
  'itsu',
  'branches',
  'only',
  'know',
  'that',
  'every',
  'business',
  'should',
  'have',
  'someone',
  'like',
  'renata',
  'and',
  'its',
  'success',
  'would',
  'be',
  'guaranteed',
  'dani'],
 ['was',
  'struggling',
  'to',
  'redeem',
  'voucher',
  'and',
  'approached',
  'the',
  'till',
  'the',
  'manager',
  'came',
  'out',
  'to',
  'help',
  'me',
  'am',
  'regular',
  'customer',
  'at',
  'the',
  'nhg',
  'branch',
  'and',
  'this',
  'woman',
  'is',
  'fantastic',
  'always',
  'smiling',
  'cheerful',
  'and',
  'extremely',
  'helpful',
  'she',
  'promotes',
  'new',
  'products',
  'helps',
  'customers',
  'and',
  'is',
  'very',
  'efficient'],
 ['the',
  'manager',
  'silverio',
  'at',
  'victoria',
  'station',
  'itsu',
  'was',
  'so',
  'kind',
  'and',
  'thoughtful',
  'on',
  'day',
  'felt',
  'unwell',
  'offering',
  'me',
  'their',
  'fabulous',
  'chicken',
  'noodle',
  'soup',
  'll',
  'be',
  'heading',
  'back',
  'again',
  'soon',
  'he',
  'made',
  'my',
  'day',
  'with',
  'moment',
  'and',
  'gesture',
  'of',
  'kindness',
  'thank',
  'you'],
 ['find',
  'itsu',
  'on',
  'the',
  'kings',
  'road',
  'chelsea',
  'very',
  'welcoming',
  'and',
  'really',
  'tasty',
  'food',
  'at',
  'reasonable',
  'price',
  'my',
  'favourite',
  'is',
  'the',
  'thai',
  'noodles',
  'which',
  'are',
  'priced',
  'just',
  'under',
  'seven',
  'pounds',
  'where',
  'else',
  'can',
  'you',
  'find',
  'such',
  'scrumptious',
  'dish',
  'for',
  'this',
  'price',
  'am',
  'handicapped',
  'on',
  'mobility',
  'scooter',
  'yet',
  'the',
  'staff',
  'and',
  'manager',
  'adrian',
  'are',
  'so',
  'gracious',
  'and',
  'always',
  'help',
  'by',
  'giving',
  'me',
  'table',
  'service',
  'they',
  'never',
  'object',
  'to',
  'my',
  'scooter',
  'being',
  'in',
  'the',
  'way',
  'it',
  'is',
  'pleasure',
  'to',
  'go',
  'to',
  'itsu',
  'on',
  'the',
  'kings',
  'rd',
  'chelsea',
  'my',
  'last',
  'visit',
  'was',
  'on',
  'february',
  'we',
  'are',
  'so',
  'lucky',
  'to',
  'have',
  'itsu',
  'locally'],
 ['my',
  'brother',
  'and',
  'visited',
  'itsu',
  'victoria',
  'station',
  'yesterday',
  'we',
  'were',
  'absolutely',
  'starving',
  'and',
  'exhausted',
  'so',
  'we',
  'grabbed',
  'some',
  'gyoza',
  'and',
  'mochi',
  'we',
  'were',
  'served',
  'by',
  'priya',
  'who',
  'was',
  'friendly',
  'smiling',
  'and',
  'extremely',
  'helpful',
  'and',
  'she',
  'gave',
  'us',
  'box',
  'of',
  'bao',
  'buns',
  'for',
  'free',
  'as',
  'it',
  'was',
  'the',
  'end',
  'of',
  'the',
  'day',
  'lovely',
  'extra',
  'at',
  'the',
  'end',
  'of',
  'long',
  'day',
  'so',
  'thank',
  'you',
  'priya'],
 ['love',
  'the',
  'food',
  'it',
  'tasty',
  'well',
  'presented',
  'and',
  'decent',
  'portion',
  'the',
  'packaging',
  'is',
  'nicely',
  'done',
  'as',
  'well',
  'ordering',
  'food',
  'using',
  'delivery',
  'services',
  'leaves',
  'food',
  'vulnerable',
  'to',
  'tampering',
  'not',
  'to',
  'mention',
  'arriving',
  'cold',
  'not',
  'only',
  'does',
  'itsu',
  'packaging',
  'keep',
  'food',
  'warm',
  'it',
  'seals',
  'the',
  'food',
  'to',
  'prevent',
  'both',
  'spills',
  'and',
  'tampering'],
 ['itsu',
  'victoria',
  'station',
  'is',
  'fabulous',
  'the',
  'staff',
  'are',
  'great',
  'the',
  'manager',
  'went',
  'over',
  'and',
  'beyond',
  'to',
  'cater',
  'for',
  'my',
  'tolerences',
  'whenever',
  'visit',
  'we',
  'are',
  'welcomed',
  'with',
  'huge',
  'smile',
  'and',
  'cheerful',
  'attitude',
  'from',
  'the',
  'manager',
  'will',
  'always',
  'visit',
  'when',
  'int',
  'he',
  'area',
  'thank',
  'you'],
 ['visited',
  'itsu',
  'wembley',
  'park',
  'today',
  'and',
  'was',
  'surprised',
  'by',
  'how',
  'friendly',
  'the',
  'staff',
  'were',
  'particularly',
  'gabriel',
  'in',
  'addition',
  'to',
  'the',
  'great',
  'service',
  'food',
  'was',
  'also',
  'good',
  'healthy',
  'and',
  'reasonably',
  'priced',
  'cannot',
  'fault',
  'it',
  'at',
  'all',
  'overall',
  'the',
  'visit',
  'made',
  'my',
  'day'],
 ['always',
  'clean',
  'and',
  'tidy',
  'fast',
  'and',
  'friendly',
  'service',
  'and',
  'plenty',
  'of',
  'condiments',
  'cutlery',
  'options',
  'and',
  'napkins',
  'available',
  'we',
  'never',
  'feel',
  'rushed',
  'off',
  'our',
  'table',
  'when',
  'we',
  've',
  'finished'],
 ['very',
  'good',
  'service',
  'and',
  'very',
  'nice',
  'people',
  'highly',
  'recommend'],
 ['early',
  'adopter',
  've',
  'been',
  'using',
  'itsu',
  'since',
  'it',
  'started',
  'and',
  'still',
  'fan',
  'the',
  'salmon',
  'went',
  'through',
  'very',
  'iffy',
  'phase',
  'for',
  'about',
  'months',
  'crunchy',
  'texture',
  'really',
  'not',
  'good',
  'but',
  'that',
  'was',
  'couple',
  'of',
  'years',
  'ago',
  'all',
  'good',
  'since',
  'there',
  'is',
  'difference',
  'between',
  'outlets',
  'whether',
  'that',
  'good',
  'or',
  'bad',
  'is',
  'subjective',
  'itsu',
  'social',
  'media',
  'person',
  'please',
  'don',
  'comment',
  'have',
  'no',
  'issue',
  'to',
  'be',
  'addressed',
  'and',
  'don',
  'need',
  'my',
  'ego',
  'stroked',
  'no',
  'disrespect',
  'intended'],
 ['was',
  'disappointed',
  'when',
  'bought',
  'sushi',
  'and',
  'realised',
  'it',
  'already',
  'had',
  'wasabi',
  'on',
  'it',
  'unfortunately',
  'do',
  'not',
  'like',
  'this',
  'so',
  'it',
  'was',
  'waste',
  'of',
  'my',
  'money',
  'simply',
  'enquired',
  'online',
  'whether',
  'it',
  'was',
  'possible',
  'in',
  'the',
  'future',
  'to',
  'get',
  'this',
  'removed',
  'sandra',
  'then',
  'went',
  'above',
  'and',
  'beyond',
  'and',
  'very',
  'kindly',
  'sent',
  'me',
  'some',
  'vouchers',
  'am',
  'impressed',
  'with',
  'their',
  'customer',
  'service',
  'and',
  'look',
  'forward',
  'to',
  'ordering',
  'sushi',
  'without',
  'wasabi',
  'in',
  'the',
  'future'],
 ['buy',
  'my',
  'lunch',
  'from',
  'itsu',
  'fairly',
  'regularly',
  'it',
  'healthy',
  'and',
  'nutritious',
  'and',
  'minimal',
  'fuss',
  'the',
  'shop',
  'near',
  'chancery',
  'lane',
  'london',
  'is',
  'small',
  'friendly',
  'and',
  'it',
  'never',
  'busy',
  'because',
  'everyone',
  'else',
  'appears',
  'to',
  'go',
  'to',
  'wasabi',
  'the',
  'only',
  'reason',
  'this',
  'review',
  'doesn',
  'have',
  'five',
  'stars',
  'is',
  'because',
  'they',
  've',
  'recently',
  'stopped',
  'selling',
  'the',
  'rice',
  'and',
  'veggie',
  'dumplings',
  'it',
  'was',
  'something',
  'that',
  'would',
  'eat',
  'with',
  'miso',
  've',
  'had',
  'to',
  'explore',
  'other',
  'options',
  'which',
  'may',
  'have',
  'meant',
  've',
  'tried',
  'more',
  'food',
  'that',
  'they',
  'sell',
  'but',
  'nothing',
  'really',
  'beats',
  'the',
  'ease',
  'and',
  'taste',
  'of',
  'the',
  'rice',
  'and',
  'dumplings',
  'bring',
  'it',
  'back'],
 ['previously',
  'gave',
  'itsu',
  'low',
  'rating',
  'but',
  'after',
  'visiting',
  'couple',
  'of',
  'times',
  'after',
  'can',
  'say',
  'that',
  'it',
  'has',
  'improved',
  'vastly',
  'the',
  'prices',
  'are',
  'still',
  'on',
  'the',
  'expensive',
  'side',
  'but',
  'the',
  'customer',
  'service',
  'is',
  'so',
  'much',
  'better',
  'thank',
  'you'],
 ['itsu',
  'is',
  'great',
  'sushi',
  'for',
  'its',
  'price',
  'one',
  'can',
  'eat',
  'well',
  'for',
  'budget',
  'price',
  'if',
  'sushi',
  'is',
  'on',
  'your',
  'lunch',
  'break',
  'it',
  'quick',
  'fresh',
  'variety',
  'is',
  'good',
  'and',
  'eating',
  'facility',
  'is',
  'good',
  'have',
  'had',
  'better',
  'sushi',
  'at',
  'high',
  'end',
  'restaurant',
  'but',
  'then',
  'the',
  'cost',
  'includes',
  'expensive',
  'drinks',
  'personal',
  'servers',
  'and',
  'top',
  'end',
  'sushi',
  'chefs',
  'for',
  'quick',
  'sushi',
  'on',
  'the',
  'go',
  'itsu',
  'is',
  'very',
  'decent',
  'and',
  'good',
  'value'],
 ['regular',
  'lunch',
  'of',
  'the',
  'chicken',
  'teryaki',
  'bowl',
  'at',
  'the',
  'soho',
  'branch',
  'always',
  'good',
  'tasty',
  'and',
  'quick',
  'pleasant',
  'service'],
 ['good',
  'service',
  'good',
  'food',
  'nice',
  'to',
  'see',
  'more',
  'tasty',
  'healthy',
  'food',
  'options',
  'maybe',
  'get',
  'rid',
  'of',
  'some',
  'of',
  'the',
  'sugary',
  'drinks',
  'on',
  'the',
  'shelves',
  'or',
  'make',
  'them',
  'smaller',
  'fish',
  'is'],
 ['average',
  'sushi',
  'but',
  'great',
  'customer',
  'experience',
  'good',
  'if',
  'you',
  'are',
  'in',
  'hurry'],
 ['it',
  'was',
  'really',
  'good',
  'no',
  'queue',
  'friendly',
  'staff',
  'and',
  'food',
  'to',
  'the',
  'ready'],
 ['like',
  'some',
  'of',
  'the',
  'food',
  'dishes',
  'and',
  'the',
  'jasmine',
  'tea',
  'and',
  'consider',
  'it',
  'good',
  'value',
  'for',
  'money',
  'have',
  'been',
  'put',
  'off',
  'at',
  'couple',
  'of',
  'locations',
  'by',
  'the',
  'excessively',
  'loud',
  'music',
  'being',
  'played',
  'turn',
  'the',
  'volume',
  'down',
  'please'],
 ['have',
  'used',
  'the',
  'just',
  'opened',
  'exeter',
  'branch',
  'of',
  'itsu',
  'times',
  'in',
  'the',
  'last',
  'or',
  'so',
  'days',
  'ive',
  'done',
  'bullet',
  'points',
  'to',
  'simplify',
  'my',
  'thoughts',
  'fitted',
  'out',
  'the',
  'premises',
  'beautifully',
  'the',
  'food',
  'is',
  'beautiful',
  'if',
  'not',
  'sometimes',
  'exactly',
  'what',
  'described',
  'in',
  'the',
  'menu',
  'put',
  'down',
  'to',
  'maybe',
  'more',
  'training',
  'or',
  'lack',
  'of',
  'experience',
  'does',
  'not',
  'accept',
  'cash',
  'this',
  'is',
  'legal',
  'tender',
  'no',
  'company',
  'should',
  'take',
  'it',
  'on',
  'themselves',
  'to',
  'ban',
  'it',
  'this',
  'particular',
  'one',
  'urks',
  'me',
  'no',
  'display',
  'of',
  'opening',
  'times',
  'on',
  'shop',
  'front',
  'funny',
  'closing',
  'times',
  'pm',
  'mon',
  'to',
  'thursday',
  'pm',
  'friday',
  'onwards',
  'seems',
  'like',
  'your',
  'missing',
  'customers',
  'as',
  'the',
  'city',
  'has',
  'very',
  'little',
  'in',
  'the',
  'way',
  'of',
  'takeaway',
  'least',
  'of',
  'all',
  'healthy',
  'alternatives',
  'my',
  'review',
  'will',
  'be',
  'adjusted',
  'as',
  'when',
  'things',
  'am',
  'sure',
  'will',
  'improve',
  'but',
  'the',
  'cash',
  'ban',
  'leaves',
  'me',
  'not',
  'recommending',
  'at',
  'this',
  'times',
  'as',
  'am',
  'strong',
  'advocate',
  'for',
  'the',
  'use',
  'of',
  'cash'],
 ['great',
  'sushi',
  'good',
  'service',
  'always',
  'consistent',
  'but',
  'really',
  'fed',
  'up',
  'with',
  'their',
  'ridiculous',
  'attitude',
  'when',
  'requesting',
  'some',
  'ginger',
  'every',
  'other',
  'boxed',
  'sushi',
  'vendor',
  'places',
  'some',
  'ginger',
  'in',
  'their',
  'offerings',
  'but',
  'itsu',
  'stopped',
  'doing',
  'this',
  'while',
  'back',
  'so',
  'ask',
  'for',
  'little',
  'ginger',
  'at',
  'the',
  'counter',
  'having',
  'been',
  'assured',
  'in',
  'writing',
  'by',
  'itsu',
  'that',
  'their',
  'policy',
  'is',
  'to',
  'provide',
  'one',
  'packet',
  'of',
  'ginger',
  'free',
  'of',
  'charge',
  'per',
  'boxed',
  'item',
  'when',
  'requested',
  'at',
  'the',
  'till',
  'this',
  'is',
  'never',
  'realised',
  'and',
  'every',
  'time',
  'we',
  'have',
  'to',
  'go',
  'through',
  'merry',
  'dance',
  'to',
  'not',
  'add',
  'ridiculously',
  'trivial',
  'for',
  'sachet',
  'this',
  'is',
  'not',
  'about',
  'the',
  'money',
  'it',
  'is',
  'the',
  'inconsistency',
  'and',
  'childishness',
  'that',
  'is',
  'the',
  'frustration'],
 ['not',
  'the',
  'worst',
  'place',
  'to',
  'work',
  'job',
  'security',
  'is',
  'there',
  'although',
  'bad',
  'hours',
  'of',
  'work',
  'and',
  'not',
  'much',
  'reliability',
  'there',
  'could',
  'have',
  'hours',
  'week',
  'could',
  'have',
  'depends',
  'staff',
  'and',
  'management',
  'usually',
  'are',
  'god',
  'awful',
  'and',
  'people',
  'are',
  'promoted',
  'on',
  'nepotism',
  'basis',
  'while',
  'hr',
  'is',
  'quite',
  'alright',
  'and',
  'ceo',
  'isn',
  'abandoning',
  'care',
  'for',
  'his',
  'employees',
  'noone',
  'got',
  'left',
  'behind',
  'during',
  'covid',
  'while',
  'pret',
  'manger',
  'fired',
  'like',
  'of',
  'their',
  'staff'],
 ['bought',
  'itsu',
  'crispy',
  'seaweed',
  'thins',
  'from',
  'supermarket',
  'my',
  'husband',
  'and',
  'absolutely',
  'love',
  'them',
  'but',
  'don',
  'want',
  'to',
  'buy',
  'them',
  'again',
  'because',
  'the',
  'amount',
  'of',
  'plastic',
  'packaging',
  'used',
  'is',
  'horrendous',
  'the',
  'individual',
  'packets',
  'contain',
  'plastic',
  'holders',
  'wrapped',
  'in',
  'plastic',
  'which',
  'are',
  'wrapped',
  'again',
  'in',
  'the',
  'outer',
  'layer',
  'of',
  'plastic',
  'keeping',
  'them',
  'together',
  'each',
  'individual',
  'packet',
  'also',
  'contains',
  'small',
  'plastic',
  'packet',
  'of',
  'substance',
  'which',
  'stops',
  'the',
  'product',
  'from',
  'spoiling',
  'appreciate',
  'that',
  'the',
  'product',
  'is',
  'very',
  'delicate',
  'but',
  'seriously',
  'there',
  'has',
  'to',
  'be',
  'more',
  'environmentally',
  'friendly',
  'way',
  'of',
  'delivering',
  'this',
  'product',
  'to',
  'customers',
  'just',
  'can',
  'bear',
  'to',

## Suppression des STOPWORDS

Comme évoqué plus haut, certains mots sont très redondants et n'apportent pas d'information : nous importons grâce à la bibliothèque Spacy, une liste prédéfinie des stopwords que nous supprimons par la suite.

In [313]:
"""
import sys
!{sys.executable} -m pip install spacy==3.7.5 
#les autres versions ne fonctionnent pas lors de l'import
"""

"\nimport sys\n!{sys.executable} -m pip install spacy==3.7.5 \n#les autres versions ne fonctionnent pas lors de l'import\n"

In [349]:
from spacy.lang.en.stop_words import STOP_WORDS as en_stop

In [350]:
#Définitions des stopwords prédéfinis à supprimer
texts = [
    [word for word in doc if word not in en_stop]
    for doc in texts
]

In [351]:
texts

[['big',
  'guy',
  'moses',
  'works',
  'itsu',
  'gatwick',
  'airport',
  'kind',
  'gentle',
  'welcoming',
  'journey',
  'better',
  'putting',
  'smile',
  'thanks',
  'moses',
  'continue',
  'shine',
  'light'],
 ['great',
  'experience',
  'itsu',
  'thanks',
  'hospitality',
  'moses',
  'gatwick',
  'airport',
  'south',
  'terminal'],
 ['itsu',
  'virgins',
  'enjoyed',
  'lovely',
  'time',
  'experience',
  'itsu',
  'liverpool',
  'street',
  'staff',
  'exceptionally',
  'good',
  'helping',
  'navigate',
  'way',
  'ordering',
  'process',
  'food',
  'hot',
  'tasty',
  'efficiently',
  'produced',
  'll',
  'certainly',
  'try',
  'itsu'],
 ['itsu',
  'brunswick',
  'centre',
  'camden',
  'extremely',
  'nice',
  'sushi',
  'place',
  'staff',
  'helpful',
  'especially',
  'ornella',
  'wojciech',
  'taught',
  'operate',
  'technology',
  'scan',
  'app',
  'claim',
  'butterflies',
  'ease',
  'taught',
  'access',
  'nhs',
  'discount',
  'thank',
  'goodness',
  'lovely',
  'staff',
  'enjoy',
  'jobs',
  'customers',
  'feel',
  'special'],
 ['itsu',
  'reading',
  'gate',
  'clean',
  'restaurant',
  'friendly',
  'staff',
  'food',
  'quick',
  'great'],
 ['year',
  'old',
  'son',
  'loves',
  'restaurant',
  'chain',
  'ordered',
  'rice',
  'box',
  'absolutely',
  'loved',
  'normally',
  'complains',
  'eating',
  'vegetables',
  'way',
  'cooked',
  'presented',
  'meant',
  'happy',
  'eat',
  'veg',
  'decor',
  'beautiful'],
 ['ate',
  'itsu',
  'restaurant',
  'brunswick',
  'centre',
  'naast',
  'de',
  'excellent',
  'food',
  'service',
  'extra',
  'special',
  'smiles',
  'genuine',
  'interest',
  'tourists',
  'visiting',
  'time',
  'quick',
  'efficient',
  'friendly'],
 ['excellent', 'service', 'lovely', 'food', 'highly', 'recommend'],
 ['itsu',
  'great',
  'menu',
  'fair',
  'prices',
  'sushi',
  'phenomenal',
  'fresh',
  'love',
  'healthier',
  'option',
  'fast',
  'food',
  'chains',
  'restaurants',
  'atmosphere',
  'inside',
  'dine',
  'great',
  'criticism',
  'including',
  'mini',
  'soy',
  'sauce',
  'bottle',
  'sushi',
  'pack',
  'wasteful',
  'think',
  'instead',
  'option',
  'mini',
  'bottle',
  'wanted',
  'packaging',
  'great',
  'apart',
  'small',
  'criticism',
  'perfect',
  'absolutely',
  'love',
  'app',
  'loyalty',
  'scheme',
  'definitely',
  'recommend',
  'amazing',
  'restaurant'],
 ['visiting',
  'brixton',
  'branch',
  'opening',
  'year',
  'ago',
  'enjoy',
  'convenience',
  'grabbing',
  'hot',
  'meal',
  'mins',
  'away',
  'office',
  'especially',
  'love',
  'poached',
  'egg',
  'add',
  'dish',
  'order',
  'tends',
  'highly',
  'recommend',
  'fancy',
  'asian',
  'inspired',
  'eat',
  'takeaway',
  'fast',
  'food',
  'thing',
  'bear',
  'mind',
  'cashless',
  'eatery',
  'old',
  'schoolers',
  'like',
  'whip',
  'card'],
 ['morning',
  'visited',
  'itsu',
  'euston',
  'station',
  'issues',
  'card',
  'machine',
  'transactions',
  'guess',
  'got',
  'lunch',
  'free',
  'touched',
  'thank',
  'itsu',
  'hope',
  'issues',
  'got',
  'solved',
  'appreciate',
  'kindness',
  'thank'],
 ['hi',
  'work',
  'bank',
  'office',
  'lunches',
  'itsu',
  'cheapside',
  'people',
  'office',
  'collecting',
  'orders',
  'work',
  'colleagues',
  'forward',
  'lunch',
  'list',
  'renata',
  'shop',
  'manager',
  'amazing',
  'quick',
  'organized',
  'counts',
  'smiling',
  'customers',
  'feels',
  'welcome',
  'experience',
  'itsu',
  'absolutely',
  'positive',
  'know',
  'itsu',
  'branches',
  'know',
  'business',
  'like',
  'renata',
  'success',
  'guaranteed',
  'dani'],
 ['struggling',
  'redeem',
  'voucher',
  'approached',
  'till',
  'manager',
  'came',
  'help',
  'regular',
  'customer',
  'nhg',
  'branch',
  'woman',
  'fantastic',
  'smiling',
  'cheerful',
  'extremely',
  'helpful',
  'promotes',
  'new',
  'products',
  'helps',
  'customers',
  'efficient'],
 ['manager',
  'silverio',
  'victoria',
  'station',
  'itsu',
  'kind',
  'thoughtful',
  'day',
  'felt',
  'unwell',
  'offering',
  'fabulous',
  'chicken',
  'noodle',
  'soup',
  'll',
  'heading',
  'soon',
  'day',
  'moment',
  'gesture',
  'kindness',
  'thank'],
 ['find',
  'itsu',
  'kings',
  'road',
  'chelsea',
  'welcoming',
  'tasty',
  'food',
  'reasonable',
  'price',
  'favourite',
  'thai',
  'noodles',
  'priced',
  'seven',
  'pounds',
  'find',
  'scrumptious',
  'dish',
  'price',
  'handicapped',
  'mobility',
  'scooter',
  'staff',
  'manager',
  'adrian',
  'gracious',
  'help',
  'giving',
  'table',
  'service',
  'object',
  'scooter',
  'way',
  'pleasure',
  'itsu',
  'kings',
  'rd',
  'chelsea',
  'visit',
  'february',
  'lucky',
  'itsu',
  'locally'],
 ['brother',
  'visited',
  'itsu',
  'victoria',
  'station',
  'yesterday',
  'absolutely',
  'starving',
  'exhausted',
  'grabbed',
  'gyoza',
  'mochi',
  'served',
  'priya',
  'friendly',
  'smiling',
  'extremely',
  'helpful',
  'gave',
  'box',
  'bao',
  'buns',
  'free',
  'end',
  'day',
  'lovely',
  'extra',
  'end',
  'long',
  'day',
  'thank',
  'priya'],
 ['love',
  'food',
  'tasty',
  'presented',
  'decent',
  'portion',
  'packaging',
  'nicely',
  'ordering',
  'food',
  'delivery',
  'services',
  'leaves',
  'food',
  'vulnerable',
  'tampering',
  'mention',
  'arriving',
  'cold',
  'itsu',
  'packaging',
  'food',
  'warm',
  'seals',
  'food',
  'prevent',
  'spills',
  'tampering'],
 ['itsu',
  'victoria',
  'station',
  'fabulous',
  'staff',
  'great',
  'manager',
  'went',
  'cater',
  'tolerences',
  'visit',
  'welcomed',
  'huge',
  'smile',
  'cheerful',
  'attitude',
  'manager',
  'visit',
  'int',
  'area',
  'thank'],
 ['visited',
  'itsu',
  'wembley',
  'park',
  'today',
  'surprised',
  'friendly',
  'staff',
  'particularly',
  'gabriel',
  'addition',
  'great',
  'service',
  'food',
  'good',
  'healthy',
  'reasonably',
  'priced',
  'fault',
  'overall',
  'visit',
  'day'],
 ['clean',
  'tidy',
  'fast',
  'friendly',
  'service',
  'plenty',
  'condiments',
  'cutlery',
  'options',
  'napkins',
  'available',
  'feel',
  'rushed',
  'table',
  've',
  'finished'],
 ['good', 'service', 'nice', 'people', 'highly', 'recommend'],
 ['early',
  'adopter',
  've',
  'itsu',
  'started',
  'fan',
  'salmon',
  'went',
  'iffy',
  'phase',
  'months',
  'crunchy',
  'texture',
  'good',
  'couple',
  'years',
  'ago',
  'good',
  'difference',
  'outlets',
  'good',
  'bad',
  'subjective',
  'itsu',
  'social',
  'media',
  'person',
  'don',
  'comment',
  'issue',
  'addressed',
  'don',
  'need',
  'ego',
  'stroked',
  'disrespect',
  'intended'],
 ['disappointed',
  'bought',
  'sushi',
  'realised',
  'wasabi',
  'unfortunately',
  'like',
  'waste',
  'money',
  'simply',
  'enquired',
  'online',
  'possible',
  'future',
  'removed',
  'sandra',
  'went',
  'kindly',
  'sent',
  'vouchers',
  'impressed',
  'customer',
  'service',
  'look',
  'forward',
  'ordering',
  'sushi',
  'wasabi',
  'future'],
 ['buy',
  'lunch',
  'itsu',
  'fairly',
  'regularly',
  'healthy',
  'nutritious',
  'minimal',
  'fuss',
  'shop',
  'near',
  'chancery',
  'lane',
  'london',
  'small',
  'friendly',
  'busy',
  'appears',
  'wasabi',
  'reason',
  'review',
  'doesn',
  'stars',
  've',
  'recently',
  'stopped',
  'selling',
  'rice',
  'veggie',
  'dumplings',
  'eat',
  'miso',
  've',
  'explore',
  'options',
  'meant',
  've',
  'tried',
  'food',
  'sell',
  'beats',
  'ease',
  'taste',
  'rice',
  'dumplings',
  'bring'],
 ['previously',
  'gave',
  'itsu',
  'low',
  'rating',
  'visiting',
  'couple',
  'times',
  'improved',
  'vastly',
  'prices',
  'expensive',
  'customer',
  'service',
  'better',
  'thank'],
 ['itsu',
  'great',
  'sushi',
  'price',
  'eat',
  'budget',
  'price',
  'sushi',
  'lunch',
  'break',
  'quick',
  'fresh',
  'variety',
  'good',
  'eating',
  'facility',
  'good',
  'better',
  'sushi',
  'high',
  'end',
  'restaurant',
  'cost',
  'includes',
  'expensive',
  'drinks',
  'personal',
  'servers',
  'end',
  'sushi',
  'chefs',
  'quick',
  'sushi',
  'itsu',
  'decent',
  'good',
  'value'],
 ['regular',
  'lunch',
  'chicken',
  'teryaki',
  'bowl',
  'soho',
  'branch',
  'good',
  'tasty',
  'quick',
  'pleasant',
  'service'],
 ['good',
  'service',
  'good',
  'food',
  'nice',
  'tasty',
  'healthy',
  'food',
  'options',
  'maybe',
  'rid',
  'sugary',
  'drinks',
  'shelves',
  'smaller',
  'fish'],
 ['average', 'sushi', 'great', 'customer', 'experience', 'good', 'hurry'],
 ['good', 'queue', 'friendly', 'staff', 'food', 'ready'],
 ['like',
  'food',
  'dishes',
  'jasmine',
  'tea',
  'consider',
  'good',
  'value',
  'money',
  'couple',
  'locations',
  'excessively',
  'loud',
  'music',
  'played',
  'turn',
  'volume'],
 ['opened',
  'exeter',
  'branch',
  'itsu',
  'times',
  'days',
  'ive',
  'bullet',
  'points',
  'simplify',
  'thoughts',
  'fitted',
  'premises',
  'beautifully',
  'food',
  'beautiful',
  'exactly',
  'described',
  'menu',
  'maybe',
  'training',
  'lack',
  'experience',
  'accept',
  'cash',
  'legal',
  'tender',
  'company',
  'ban',
  'particular',
  'urks',
  'display',
  'opening',
  'times',
  'shop',
  'funny',
  'closing',
  'times',
  'pm',
  'mon',
  'thursday',
  'pm',
  'friday',
  'onwards',
  'like',
  'missing',
  'customers',
  'city',
  'little',
  'way',
  'takeaway',
  'healthy',
  'alternatives',
  'review',
  'adjusted',
  'things',
  'sure',
  'improve',
  'cash',
  'ban',
  'leaves',
  'recommending',
  'times',
  'strong',
  'advocate',
  'use',
  'cash'],
 ['great',
  'sushi',
  'good',
  'service',
  'consistent',
  'fed',
  'ridiculous',
  'attitude',
  'requesting',
  'ginger',
  'boxed',
  'sushi',
  'vendor',
  'places',
  'ginger',
  'offerings',
  'itsu',
  'stopped',
  'ask',
  'little',
  'ginger',
  'counter',
  'having',
  'assured',
  'writing',
  'itsu',
  'policy',
  'provide',
  'packet',
  'ginger',
  'free',
  'charge',
  'boxed',
  'item',
  'requested',
  'till',
  'realised',
  'time',
  'merry',
  'dance',
  'add',
  'ridiculously',
  'trivial',
  'sachet',
  'money',
  'inconsistency',
  'childishness',
  'frustration'],
 ['worst',
  'place',
  'work',
  'job',
  'security',
  'bad',
  'hours',
  'work',
  'reliability',
  'hours',
  'week',
  'depends',
  'staff',
  'management',
  'usually',
  'god',
  'awful',
  'people',
  'promoted',
  'nepotism',
  'basis',
  'hr',
  'alright',
  'ceo',
  'isn',
  'abandoning',
  'care',
  'employees',
  'got',
  'left',
  'covid',
  'pret',
  'manger',
  'fired',
  'like',
  'staff'],
 ['bought',
  'itsu',
  'crispy',
  'seaweed',
  'thins',
  'supermarket',
  'husband',
  'absolutely',
  'love',
  'don',
  'want',
  'buy',
  'plastic',
  'packaging',
  'horrendous',
  'individual',
  'packets',
  'contain',
  'plastic',
  'holders',
  'wrapped',
  'plastic',
  'wrapped',
  'outer',
  'layer',
  'plastic',
  'keeping',
  'individual',
  'packet',
  'contains',
  'small',
  'plastic',
  'packet',
  'substance',
  'stops',
  'product',
  'spoiling',
  'appreciate',
  'product',
  'delicate',
  'seriously',
  'environmentally',
  'friendly',
  'way',
  'delivering',
  'product',
  'customers',
  'bear',
  'throw',
  'packet',
  'packet',
  'bin',
  'address',
  'issue'],
 ['got',
  'lloyds',
  'bank',
  'world',
  'elite',
  'card',
  'invited',
  'sign',
  'itsu',
  'rewards',
  'partners',
  'decided',
  'itsu',
  'went',
  'baths',
  'store',
  'gyoza',
  'firstly',
  'couldn',
  'use',
  'app',
  'kept',
  'saying',
  'wouldn',
  'scan',
  'couldn',
  'work',
  'ordered',
  'went',
  'counter',
  'said',
  'able',
  'add',
  'butterflies',
  'account',
  'felt',
  'weird',
  'told',
  'couldn',
  'needed',
  'spend',
  'fiver',
  'explained',
  'told',
  'website',
  'help',
  'nope',
  'help',
  'whatsoever',
  'option',
  'able',
  'ask',
  'general',
  'question',
  'help',
  'decided',
  'message',
  'marketing',
  'upload',
  'photo',
  'food',
  'receipt',
  'nope',
  'crashed',
  'said',
  'issue',
  'great',
  'service'],
 ['looked',
  'menu',
  'online',
  'looked',
  'delicious',
  'presented',
  'bowl',
  'day',
  'ordering',
  'showed',
  'dish',
  'bowl',
  'ordering',
  'gave',
  'cardboard',
  'tub',
  'thought',
  'watery',
  'slop',
  'flavoured',
  'water',
  'overpriced'],
 ['food',
  'okay',
  'special',
  'annoyed',
  'ordered',
  'english',
  'breakfast',
  'tea',
  'london',
  'find',
  'provided',
  'milk',
  'sort',
  'simply',
  'sloppy',
  'tried',
  'drink',
  'black',
  'disgusting'],
 ['special',
  'honest',
  'don',
  'support',
  'companies',
  'charge',
  'sit',
  'eat',
  'customers',
  'pay',
  'tax',
  'know',
  'lot',
  'companies',
  'rule',
  'apparently',
  'apply',
  'hot',
  'food',
  'told',
  'items',
  'apply',
  'sushi',
  'pretty',
  'good',
  'fresh',
  'sure',
  'ingredients',
  'particularly',
  'sauces',
  'companies',
  'sell',
  'sort',
  'food',
  'use',
  'msg',
  'particularly',
  'nasty',
  'ingredient',
  'asked',
  'staff',
  'told',
  'know',
  'msg',
  'look',
  'web',
  'site',
  'yo',
  'sushi',
  'informed',
  'checked',
  'told',
  'products',
  'like',
  'soup',
  'contain',
  'surprised',
  'lack',
  'training',
  'itsu',
  'particularly',
  'ordeal',
  'pret',
  'people',
  'allergies',
  'consequence',
  'customers',
  'asked',
  'allergy',
  'sulfites',
  'thing',
  'don',
  'like',
  'allergy',
  'wagamama',
  'sauces',
  'preservative',
  'summarise',
  'research',
  'use',
  'particularly',
  'soups',
  'sauces',
  'surprised',
  'place',
  'eat',
  'regularly',
  'causing',
  'problems',
  'long',
  'term',
  'ingredients',
  'good',
  'don',
  'mislead',
  'fact',
  'things',
  'like',
  'sushi',
  'considered',
  'good',
  'case',
  'look',
  'add',
  'dishes',
  'going',
  'update',
  'review',
  'soon',
  'update',
  'concerning',
  'msg',
  'sulfites'],
 ['question',
  'different',
  'price',
  'vegetable',
  'dumplings',
  'hot',
  'priced',
  'cold',
  'makes',
  'sense'],
 ['thier',
  'dirty',
  'don',
  'clean',
  'sanitise',
  'thier',
  'counter',
  'tops',
  'trays',
  'use',
  'eat',
  'food',
  'fly',
  'hovering',
  'staff',
  'rude',
  'overbearing',
  'suchi',
  'falling',
  'apart',
  'picked',
  'chop',
  'sticks',
  'dumplings',
  'miso',
  'soup',
  'falling',
  'apart',
  'makes',
  'soup',
  'look',
  'uninviting',
  'puts',
  'eating',
  'honest',
  'thier',
  'toilets',
  'aren',
  'clean',
  'men',
  'women',
  'share',
  'toilet',
  'odd',
  'putting'],
 ['gotten',
  'chicken',
  'teriyaki',
  'rice',
  'bowl',
  'foods',
  'recent',
  'time',
  'gotten',
  'chicken',
  'teriyaki',
  'rice',
  'bowl',
  'gave',
  'food',
  'poisoning',
  'remember',
  'looking',
  'chicken',
  'thinking',
  'looked',
  'funny',
  'ignored',
  'eaten',
  'worst',
  'food',
  'poisoning',
  'hot',
  'hot',
  'fever',
  'chills'],
 ['went',
  'itsu',
  'eat',
  'beautiful',
  'fosse',
  'park',
  'leicester',
  'week',
  'time',
  'customer',
  'service',
  'welcoming',
  'return',
  'smile',
  'welcoming',
  'begrudgingly',
  'wanted',
  'spend',
  'money',
  'opted',
  'salmon',
  'salad',
  'box',
  'promotional',
  'offer',
  'looked',
  'good',
  'similar',
  'photo',
  'unfortunately',
  'stingy',
  'small',
  'piece',
  'salmon',
  'cheap',
  'brown',
  'rice',
  'beans',
  'stuff',
  'tasted',
  'bland',
  'flavour',
  'dip',
  'comes',
  'boring',
  'definitely',
  'lacked',
  'flavour',
  'wouldn',
  'come',
  'greggs',
  'sandwich',
  'door',
  'flavour'],
 ['feel',
  'like',
  'menu',
  'got',
  'boring',
  'cheaper',
  'terms',
  'quality',
  'tasty',
  'lot',
  'ingredients',
  'hard',
  'digest',
  'like',
  'combine',
  'uncooked',
  'cabbages',
  'kale',
  'onions',
  'etc',
  'dish',
  'designs',
  'menus',
  'feel',
  'bloated',
  'time',
  'itsu',
  'got',
  'lot',
  'expensive',
  'menu',
  'feels',
  'tired',
  'app',
  'finally',
  'got',
  'bit',
  'better',
  'buggy',
  'interface',
  'freebies',
  'intuitive',
  'need',
  'member',
  'staff',
  'time',
  'trouble',
  'shoot',
  'favourite',
  'lunch',
  'spot',
  'forgot',
  'bring',
  'lunch',
  'closest',
  'office'],
 ['tried',
  'itsu',
  'products',
  'supermarket',
  'time',
  'teriyaki',
  'chicken',
  'bao',
  'buns',
  'mm',
  'filling',
  'taste',
  'bun',
  'pork',
  'gyoza',
  'filling',
  'flavour',
  'reason',
  'gave',
  'review',
  'stuffed',
  'green',
  'chile',
  'pancakes',
  'reasonable',
  'filling',
  'flavour',
  'daughter',
  'mentioned',
  'generally',
  'liked',
  'itsu',
  'products',
  'gave',
  'rest',
  'freezer',
  'day',
  'told',
  'bao',
  'buns',
  'ridiculously',
  'small',
  'filling',
  'unusual',
  'factory',
  'error',
  'company',
  'cutting',
  'ingredients',
  'rip',
  'customer'],
 ['food',
  'okay',
  'pretty',
  'good',
  'good',
  'overpriced',
  'app',
  'didn',
  'work',
  'told',
  'restaurant',
  'manager',
  'way',
  'add',
  'credits',
  'later',
  'going',
  'launch',
  'loyalty',
  'scheme',
  'right',
  'anti',
  'loyalty',
  'scheme'],
 ['love',
  'going',
  'itsu',
  'point',
  'work',
  'lunch',
  'breaks',
  'recently',
  'ordering',
  'avocado',
  'sushi',
  'salmon',
  'set',
  'noticed',
  'pea',
  'sized',
  'dot',
  'wasabi',
  'tucked',
  'underneath',
  'sushi',
  'salmon',
  'tastes',
  'extremely',
  'unpleasant',
  'option',
  'like',
  'sushi',
  'restaurants',
  'wasabi',
  'inside',
  'sushi',
  'doesn',
  'option',
  'avocado',
  'salmon',
  'sushi',
  'wasabi',
  'inside',
  'roll',
  'disappointed'],
 ['price',
  'sushi',
  'getting',
  'tired',
  'endless',
  'undercooked',
  'slightly',
  'crunchy',
  'wet',
  'sushi',
  'rice',
  'normal',
  'mirin',
  'moisture',
  'wet',
  'soggy',
  'want',
  'customers',
  'need',
  'basic',
  'ingredient',
  'correctly',
  'prepared',
  'makes',
  'feel',
  'ill',
  'need',
  'find',
  'way',
  'disposable',
  'plastic',
  'losing',
  'eat',
  'anymore',
  'hanover',
  'square',
  'branch'],
 ['itsu',
  'stansted',
  'airport',
  'tried',
  'pay',
  'cash',
  'found',
  'itsu',
  'cashless',
  'mild',
  'annoyance',
  'live',
  'wasn',
  'okay',
  'cash',
  'register',
  'display',
  'said',
  'card',
  'preferred',
  'pointed',
  'somewhat',
  'obnoxious',
  'itsu',
  'employee',
  'pointed',
  'tiny',
  'little',
  'label',
  'said',
  'card',
  'card',
  'machine',
  'going',
  'cashless',
  'clear',
  'customers',
  'choice',
  'asked',
  'pay',
  'likes',
  'told',
  'cash',
  'worthless',
  'oh',
  'sushi',
  'rice',
  'undercooked',
  'occasions'],
 ['poor',
  'experience',
  'new',
  'reading',
  'gate',
  'location',
  'food',
  'cooked',
  'dumplings',
  'rubbery',
  'cold',
  'centre',
  'service',
  'glum',
  'faces',
  'second',
  'visit',
  'row',
  'staff',
  'slamming',
  'self',
  'surface',
  'bin',
  'doors',
  'emptied',
  'shame',
  'high',
  'hopes',
  'table',
  'agreed',
  'food',
  'prepared',
  'priced',
  'sure',
  'going',
  'hear',
  'improved',
  'let',
  'hope',
  'teething',
  'problems',
  'new',
  'branch',
  'reading',
  'reviews',
  'wonder',
  'itsu',
  'wider',
  'issues',
  'network'],
 ['sunday',
  'normally',
  'reading',
  'town',
  'end',
  'having',
  'favourite',
  'itsu',
  'coconut',
  'soup',
  'consist',
  'rice',
  'greens',
  'juicy',
  'bits',
  'chicken',
  'normally',
  'bream',
  'tasteful',
  'coconut',
  'flavoured',
  'soup',
  'visited',
  'today',
  'ordered',
  'favourite',
  'disappointed',
  'water',
  'possibly',
  'counted',
  'rice',
  'grains',
  'normally',
  'staple',
  'soup',
  'bits',
  'chicken',
  'bits',
  'greens',
  'wonder',
  'significantly',
  'reduced',
  'paid',
  'liquid',
  'little',
  'content',
  'disappointed',
  'customer'],
 ['rude',
  'staff',
  'bristol',
  'temple',
  'meads',
  'cutlery',
  'eating',
  'food',
  'chopsticks',
  'use',

Ici, on voit qu'on perd le "up" de "big up", qui peut prêter à confusion, on fait le choix de tout de même continuer 
et de créer les n-grams a posteriori car nous conservons la valeurs positive de la phrase

# Création de n-grams
Si nous prenons New York par exemple, ce mot est en fait composé de deux noms disctincts. Au final, notre fonction word_count ne prendra pas en compte le mot en une fois mais "New" et "York", afin de palier à ce problème la création de bigram/trigram nous permet de lier les mots qui se retrouvent souvent entre eux : on identifie les mots qui sont souvent collés et nous les regroupons : augmentation de l'interprétabilité pour le topic modeling.

In [317]:
from gensim.models.phrases import Phraser
from gensim.models import Word2Vec, Phrases, KeyedVectors

In [359]:
# Création de bigram 
def create_bigrams(texts, min_count=5, threshold=5, as_str=False):

    bigram_model = Phraser(
        Phrases(texts, min_count=min_count, threshold=threshold)
    )

    texts_bigram = [bigram_model[doc] for doc in texts]

    if as_str:
        return [" ".join(doc) for doc in texts_bigram]

    return texts_bigram

#Création de trigram
def create_trigrams(texts, min_count_bigram=15,
                    min_count_trigram=10,
                    threshold=10,
                    as_str=False):

    # Bigrams
    bigram_model = Phraser(
        Phrases(texts,
                min_count=min_count_bigram,
                threshold=threshold)
    )

    texts_bigram = [bigram_model[doc] for doc in texts]

    # Trigrams
    trigram_model = Phraser(
        Phrases(texts_bigram,
                min_count=min_count_trigram,
                threshold=threshold)
    )

    texts_trigram = [trigram_model[doc] for doc in texts_bigram]

    if as_str:
        return [" ".join(doc) for doc in texts_trigram]

    return texts_trigram

In [360]:
texts = create_bigrams(texts)
texts = create_trigrams(texts)

In [361]:
texts

[['big',
  'guy',
  'moses',
  'works',
  'itsu',
  'gatwick',
  'airport',
  'kind',
  'gentle',
  'welcoming',
  'journey',
  'better',
  'putting',
  'smile',
  'thanks',
  'moses',
  'continue',
  'shine',
  'light'],
 ['great_experience',
  'itsu',
  'thanks',
  'hospitality',
  'moses',
  'gatwick',
  'airport',
  'south',
  'terminal'],
 ['itsu',
  'virgins',
  'enjoyed',
  'lovely',
  'time',
  'experience',
  'itsu',
  'liverpool',
  'street',
  'staff',
  'exceptionally',
  'good',
  'helping',
  'navigate',
  'way',
  'ordering_process',
  'food',
  'hot',
  'tasty',
  'efficiently',
  'produced',
  'll',
  'certainly',
  'try',
  'itsu'],
 ['itsu',
  'brunswick',
  'centre',
  'camden',
  'extremely',
  'nice',
  'sushi',
  'place',
  'staff_helpful',
  'especially',
  'ornella',
  'wojciech',
  'taught',
  'operate',
  'technology',
  'scan',
  'app',
  'claim',
  'butterflies',
  'ease',
  'taught',
  'access',
  'nhs',
  'discount',
  'thank',
  'goodness',
  'lovely',
  'staff',
  'enjoy',
  'jobs',
  'customers',
  'feel',
  'special'],
 ['itsu',
  'reading',
  'gate',
  'clean',
  'restaurant',
  'friendly_staff',
  'food',
  'quick',
  'great'],
 ['year_old',
  'son',
  'loves',
  'restaurant',
  'chain',
  'ordered',
  'rice',
  'box',
  'absolutely_loved',
  'normally',
  'complains',
  'eating',
  'vegetables',
  'way',
  'cooked',
  'presented',
  'meant',
  'happy',
  'eat',
  'veg',
  'decor',
  'beautiful'],
 ['ate',
  'itsu',
  'restaurant',
  'brunswick',
  'centre',
  'naast',
  'de',
  'excellent',
  'food',
  'service',
  'extra',
  'special',
  'smiles',
  'genuine',
  'interest',
  'tourists',
  'visiting',
  'time',
  'quick_efficient',
  'friendly'],
 ['excellent_service', 'lovely', 'food', 'highly_recommend'],
 ['itsu',
  'great',
  'menu',
  'fair',
  'prices',
  'sushi',
  'phenomenal',
  'fresh',
  'love',
  'healthier',
  'option',
  'fast_food',
  'chains',
  'restaurants',
  'atmosphere',
  'inside',
  'dine',
  'great',
  'criticism',
  'including',
  'mini',
  'soy_sauce',
  'bottle',
  'sushi',
  'pack',
  'wasteful',
  'think',
  'instead',
  'option',
  'mini',
  'bottle',
  'wanted',
  'packaging',
  'great',
  'apart',
  'small',
  'criticism',
  'perfect',
  'absolutely_love',
  'app',
  'loyalty',
  'scheme',
  'definitely_recommend',
  'amazing',
  'restaurant'],
 ['visiting',
  'brixton',
  'branch',
  'opening',
  'year_ago',
  'enjoy',
  'convenience',
  'grabbing',
  'hot',
  'meal',
  'mins',
  'away',
  'office',
  'especially',
  'love',
  'poached',
  'egg',
  'add',
  'dish',
  'order',
  'tends',
  'highly_recommend',
  'fancy',
  'asian',
  'inspired',
  'eat',
  'takeaway',
  'fast_food',
  'thing',
  'bear',
  'mind',
  'cashless',
  'eatery',
  'old',
  'schoolers',
  'like',
  'whip',
  'card'],
 ['morning',
  'visited',
  'itsu',
  'euston',
  'station',
  'issues',
  'card_machine',
  'transactions',
  'guess',
  'got',
  'lunch',
  'free',
  'touched',
  'thank',
  'itsu',
  'hope',
  'issues',
  'got',
  'solved',
  'appreciate',
  'kindness',
  'thank'],
 ['hi',
  'work',
  'bank',
  'office',
  'lunches',
  'itsu',
  'cheapside',
  'people',
  'office',
  'collecting',
  'orders',
  'work',
  'colleagues',
  'forward',
  'lunch',
  'list',
  'renata',
  'shop',
  'manager',
  'amazing',
  'quick',
  'organized',
  'counts',
  'smiling',
  'customers',
  'feels',
  'welcome',
  'experience',
  'itsu',
  'absolutely',
  'positive',
  'know',
  'itsu',
  'branches',
  'know',
  'business',
  'like',
  'renata',
  'success',
  'guaranteed',
  'dani'],
 ['struggling',
  'redeem',
  'voucher',
  'approached',
  'till',
  'manager_came',
  'help',
  'regular_customer',
  'nhg',
  'branch',
  'woman',
  'fantastic',
  'smiling',
  'cheerful',
  'extremely_helpful',
  'promotes',
  'new',
  'products',
  'helps',
  'customers',
  'efficient'],
 ['manager',
  'silverio',
  'victoria',
  'station',
  'itsu',
  'kind',
  'thoughtful',
  'day',
  'felt',
  'unwell',
  'offering',
  'fabulous',
  'chicken',
  'noodle',
  'soup',
  'll',
  'heading',
  'soon',
  'day',
  'moment',
  'gesture',
  'kindness',
  'thank'],
 ['find',
  'itsu',
  'kings',
  'road',
  'chelsea',
  'welcoming',
  'tasty',
  'food',
  'reasonable_price',
  'favourite',
  'thai',
  'noodles',
  'priced',
  'seven',
  'pounds',
  'find',
  'scrumptious',
  'dish',
  'price',
  'handicapped',
  'mobility',
  'scooter',
  'staff',
  'manager',
  'adrian',
  'gracious',
  'help',
  'giving',
  'table',
  'service',
  'object',
  'scooter',
  'way',
  'pleasure',
  'itsu',
  'kings',
  'rd',
  'chelsea',
  'visit',
  'february',
  'lucky',
  'itsu',
  'locally'],
 ['brother',
  'visited',
  'itsu',
  'victoria',
  'station',
  'yesterday',
  'absolutely',
  'starving',
  'exhausted',
  'grabbed',
  'gyoza',
  'mochi',
  'served',
  'priya',
  'friendly',
  'smiling',
  'extremely_helpful',
  'gave',
  'box',
  'bao_buns',
  'free',
  'end',
  'day',
  'lovely',
  'extra',
  'end',
  'long',
  'day',
  'thank',
  'priya'],
 ['love',
  'food',
  'tasty',
  'presented',
  'decent',
  'portion',
  'packaging',
  'nicely',
  'ordering',
  'food',
  'delivery_services',
  'leaves',
  'food',
  'vulnerable',
  'tampering',
  'mention',
  'arriving',
  'cold',
  'itsu',
  'packaging',
  'food',
  'warm',
  'seals',
  'food',
  'prevent',
  'spills',
  'tampering'],
 ['itsu',
  'victoria',
  'station',
  'fabulous',
  'staff',
  'great',
  'manager',
  'went',
  'cater',
  'tolerences',
  'visit',
  'welcomed',
  'huge',
  'smile',
  'cheerful',
  'attitude',
  'manager',
  'visit',
  'int',
  'area',
  'thank'],
 ['visited',
  'itsu',
  'wembley',
  'park',
  'today',
  'surprised',
  'friendly_staff',
  'particularly',
  'gabriel',
  'addition',
  'great_service',
  'food',
  'good',
  'healthy',
  'reasonably_priced',
  'fault',
  'overall',
  'visit',
  'day'],
 ['clean',
  'tidy',
  'fast',
  'friendly_service',
  'plenty',
  'condiments',
  'cutlery',
  'options',
  'napkins',
  'available',
  'feel',
  'rushed',
  'table',
  've',
  'finished'],
 ['good_service', 'nice', 'people', 'highly_recommend'],
 ['early',
  'adopter',
  've',
  'itsu',
  'started',
  'fan',
  'salmon',
  'went',
  'iffy',
  'phase',
  'months',
  'crunchy',
  'texture',
  'good',
  'couple',
  'years_ago',
  'good',
  'difference',
  'outlets',
  'good',
  'bad',
  'subjective',
  'itsu',
  'social_media',
  'person',
  'don',
  'comment',
  'issue',
  'addressed',
  'don_need',
  'ego',
  'stroked',
  'disrespect',
  'intended'],
 ['disappointed',
  'bought',
  'sushi',
  'realised',
  'wasabi',
  'unfortunately',
  'like',
  'waste_money',
  'simply',
  'enquired',
  'online',
  'possible',
  'future',
  'removed',
  'sandra',
  'went',
  'kindly',
  'sent',
  'vouchers',
  'impressed',
  'customer_service',
  'look_forward',
  'ordering',
  'sushi',
  'wasabi',
  'future'],
 ['buy',
  'lunch',
  'itsu',
  'fairly',
  'regularly',
  'healthy',
  'nutritious',
  'minimal',
  'fuss',
  'shop',
  'near',
  'chancery',
  'lane',
  'london',
  'small',
  'friendly',
  'busy',
  'appears',
  'wasabi',
  'reason',
  'review',
  'doesn',
  'stars',
  've',
  'recently',
  'stopped',
  'selling',
  'rice',
  'veggie',
  'dumplings',
  'eat',
  'miso',
  've',
  'explore',
  'options',
  'meant',
  've_tried',
  'food',
  'sell',
  'beats',
  'ease',
  'taste',
  'rice',
  'dumplings',
  'bring'],
 ['previously',
  'gave',
  'itsu',
  'low',
  'rating',
  'visiting',
  'couple_times',
  'improved',
  'vastly',
  'prices',
  'expensive',
  'customer_service',
  'better',
  'thank'],
 ['itsu',
  'great',
  'sushi',
  'price',
  'eat',
  'budget',
  'price',
  'sushi',
  'lunch',
  'break',
  'quick',
  'fresh',
  'variety',
  'good',
  'eating',
  'facility',
  'good',
  'better',
  'sushi',
  'high',
  'end',
  'restaurant',
  'cost',
  'includes',
  'expensive',
  'drinks',
  'personal',
  'servers',
  'end',
  'sushi',
  'chefs',
  'quick',
  'sushi',
  'itsu',
  'decent',
  'good_value'],
 ['regular',
  'lunch',
  'chicken',
  'teryaki',
  'bowl',
  'soho',
  'branch',
  'good',
  'tasty',
  'quick',
  'pleasant',
  'service'],
 ['good_service',
  'good',
  'food',
  'nice',
  'tasty',
  'healthy',
  'food',
  'options',
  'maybe',
  'rid',
  'sugary',
  'drinks',
  'shelves',
  'smaller',
  'fish'],
 ['average', 'sushi', 'great', 'customer_experience', 'good', 'hurry'],
 ['good', 'queue', 'friendly_staff', 'food', 'ready'],
 ['like',
  'food',
  'dishes',
  'jasmine',
  'tea',
  'consider',
  'good_value_money',
  'couple',
  'locations',
  'excessively',
  'loud',
  'music',
  'played',
  'turn',
  'volume'],
 ['opened',
  'exeter',
  'branch',
  'itsu',
  'times',
  'days',
  'ive',
  'bullet',
  'points',
  'simplify',
  'thoughts',
  'fitted',
  'premises',
  'beautifully',
  'food',
  'beautiful',
  'exactly',
  'described',
  'menu',
  'maybe',
  'training',
  'lack',
  'experience',
  'accept',
  'cash',
  'legal',
  'tender',
  'company',
  'ban',
  'particular',
  'urks',
  'display',
  'opening',
  'times',
  'shop',
  'funny',
  'closing',
  'times',
  'pm',
  'mon',
  'thursday',
  'pm',
  'friday',
  'onwards',
  'like',
  'missing',
  'customers',
  'city',
  'little',
  'way',
  'takeaway',
  'healthy',
  'alternatives',
  'review',
  'adjusted',
  'things',
  'sure',
  'improve',
  'cash',
  'ban',
  'leaves',
  'recommending',
  'times',
  'strong',
  'advocate',
  'use',
  'cash'],
 ['great',
  'sushi',
  'good_service',
  'consistent',
  'fed',
  'ridiculous',
  'attitude',
  'requesting',
  'ginger',
  'boxed',
  'sushi',
  'vendor',
  'places',
  'ginger',
  'offerings',
  'itsu',
  'stopped',
  'ask',
  'little',
  'ginger',
  'counter',
  'having',
  'assured',
  'writing',
  'itsu',
  'policy',
  'provide',
  'packet',
  'ginger',
  'free_charge',
  'boxed',
  'item',
  'requested',
  'till',
  'realised',
  'time',
  'merry',
  'dance',
  'add',
  'ridiculously',
  'trivial',
  'sachet',
  'money',
  'inconsistency',
  'childishness',
  'frustration'],
 ['worst',
  'place',
  'work',
  'job',
  'security',
  'bad',
  'hours',
  'work',
  'reliability',
  'hours',
  'week',
  'depends',
  'staff',
  'management',
  'usually',
  'god',
  'awful',
  'people',
  'promoted',
  'nepotism',
  'basis',
  'hr',
  'alright',
  'ceo',
  'isn',
  'abandoning',
  'care',
  'employees',
  'got',
  'left',
  'covid',
  'pret',
  'manger',
  'fired',
  'like',
  'staff'],
 ['bought',
  'itsu',
  'crispy',
  'seaweed',
  'thins',
  'supermarket',
  'husband',
  'absolutely_love',
  'don_want',
  'buy',
  'plastic_packaging',
  'horrendous',
  'individual',
  'packets',
  'contain',
  'plastic',
  'holders',
  'wrapped',
  'plastic',
  'wrapped',
  'outer',
  'layer',
  'plastic',
  'keeping',
  'individual',
  'packet',
  'contains',
  'small',
  'plastic',
  'packet',
  'substance',
  'stops',
  'product',
  'spoiling',
  'appreciate',
  'product',
  'delicate',
  'seriously',
  'environmentally',
  'friendly',
  'way',
  'delivering',
  'product',
  'customers',
  'bear',
  'throw',
  'packet',
  'packet',
  'bin',
  'address',
  'issue'],
 ['got',
  'lloyds',
  'bank',
  'world',
  'elite',
  'card',
  'invited',
  'sign',
  'itsu',
  'rewards',
  'partners',
  'decided',
  'itsu',
  'went',
  'baths',
  'store',
  'gyoza',
  'firstly',
  'couldn',
  'use_app',
  'kept',
  'saying',
  'wouldn',
  'scan',
  'couldn',
  'work',
  'ordered',
  'went',
  'counter',
  'said',
  'able',
  'add',
  'butterflies',
  'account',
  'felt',
  'weird',
  'told',
  'couldn',
  'needed',
  'spend',
  'fiver',
  'explained',
  'told',
  'website',
  'help',
  'nope',
  'help',
  'whatsoever',
  'option',
  'able',
  'ask',
  'general',
  'question',
  'help',
  'decided',
  'message',
  'marketing',
  'upload',
  'photo',
  'food',
  'receipt',
  'nope',
  'crashed',
  'said',
  'issue',
  'great_service'],
 ['looked',
  'menu',
  'online',
  'looked',
  'delicious',
  'presented',
  'bowl',
  'day',
  'ordering',
  'showed',
  'dish',
  'bowl',
  'ordering',
  'gave',
  'cardboard',
  'tub',
  'thought',
  'watery',
  'slop',
  'flavoured',
  'water',
  'overpriced'],
 ['food_okay',
  'special',
  'annoyed',
  'ordered',
  'english',
  'breakfast',
  'tea',
  'london',
  'find',
  'provided',
  'milk',
  'sort',
  'simply',
  'sloppy',
  'tried',
  'drink',
  'black',
  'disgusting'],
 ['special',
  'honest',
  'don',
  'support',
  'companies',
  'charge',
  'sit',
  'eat',
  'customers',
  'pay',
  'tax',
  'know',
  'lot',
  'companies',
  'rule',
  'apparently',
  'apply',
  'hot',
  'food',
  'told',
  'items',
  'apply',
  'sushi',
  'pretty_good',
  'fresh',
  'sure',
  'ingredients',
  'particularly',
  'sauces',
  'companies',
  'sell',
  'sort',
  'food',
  'use',
  'msg',
  'particularly',
  'nasty',
  'ingredient',
  'asked',
  'staff',
  'told',
  'know',
  'msg',
  'look',
  'web_site',
  'yo_sushi',
  'informed',
  'checked',
  'told',
  'products',
  'like',
  'soup',
  'contain',
  'surprised',
  'lack',
  'training',
  'itsu',
  'particularly',
  'ordeal',
  'pret',
  'people',
  'allergies',
  'consequence',
  'customers',
  'asked',
  'allergy',
  'sulfites',
  'thing',
  'don_like',
  'allergy',
  'wagamama',
  'sauces',
  'preservative',
  'summarise',
  'research',
  'use',
  'particularly',
  'soups',
  'sauces',
  'surprised',
  'place',
  'eat',
  'regularly',
  'causing',
  'problems',
  'long',
  'term',
  'ingredients',
  'good',
  'don',
  'mislead',
  'fact',
  'things',
  'like',
  'sushi',
  'considered',
  'good',
  'case',
  'look',
  'add',
  'dishes',
  'going',
  'update',
  'review',
  'soon',
  'update',
  'concerning',
  'msg',
  'sulfites'],
 ['question',
  'different',
  'price',
  'vegetable',
  'dumplings',
  'hot',
  'priced',
  'cold',
  'makes_sense'],
 ['thier',
  'dirty',
  'don',
  'clean',
  'sanitise',
  'thier',
  'counter',
  'tops',
  'trays',
  'use',
  'eat',
  'food',
  'fly',
  'hovering',
  'staff_rude',
  'overbearing',
  'suchi',
  'falling',
  'apart',
  'picked',
  'chop',
  'sticks',
  'dumplings',
  'miso_soup',
  'falling',
  'apart',
  'makes',
  'soup',
  'look',
  'uninviting',
  'puts',
  'eating',
  'honest',
  'thier',
  'toilets',
  'aren',
  'clean',
  'men',
  'women',
  'share',
  'toilet',
  'odd',
  'putting'],
 ['gotten',
  'chicken_teriyaki',
  'rice_bowl',
  'foods',
  'recent',
  'time',
  'gotten',
  'chicken_teriyaki',
  'rice_bowl',
  'gave',
  'food_poisoning',
  'remember',
  'looking',
  'chicken',
  'thinking',
  'looked',
  'funny',
  'ignored',
  'eaten',
  'worst',
  'food_poisoning',
  'hot',
  'hot',
  'fever',
  'chills'],
 ['went',
  'itsu',
  'eat',
  'beautiful',
  'fosse',
  'park',
  'leicester',
  'week',
  'time',
  'customer_service',
  'welcoming',
  'return',
  'smile',
  'welcoming',
  'begrudgingly',
  'wanted',
  'spend_money',
  'opted',
  'salmon',
  'salad',
  'box',
  'promotional',
  'offer',
  'looked',
  'good',
  'similar',
  'photo',
  'unfortunately',
  'stingy',
  'small',
  'piece',
  'salmon',
  'cheap',
  'brown',
  'rice',
  'beans',
  'stuff',
  'tasted',
  'bland',
  'flavour',
  'dip',
  'comes',
  'boring',
  'definitely',
  'lacked',
  'flavour',
  'wouldn',
  'come',
  'greggs',
  'sandwich',
  'door',
  'flavour'],
 ['feel_like',
  'menu',
  'got',
  'boring',
  'cheaper',
  'terms',
  'quality',
  'tasty',
  'lot',
  'ingredients',
  'hard',
  'digest',
  'like',
  'combine',
  'uncooked',
  'cabbages',
  'kale',
  'onions',
  'etc',
  'dish',
  'designs',
  'menus',
  'feel',
  'bloated',
  'time',
  'itsu',
  'got',
  'lot',
  'expensive',
  'menu',
  'feels',
  'tired',
  'app',
  'finally_got',
  'bit',
  'better',
  'buggy',
  'interface',
  'freebies',
  'intuitive',
  'need',
  'member_staff',
  'time',
  'trouble',
  'shoot',
  'favourite',
  'lunch',
  'spot',
  'forgot',
  'bring',
  'lunch',
  'closest',
  'office'],
 ['tried',
  'itsu',
  'products',
  'supermarket',
  'time',
  'teriyaki',
  'chicken',
  'bao_buns',
  'mm',
  'filling',
  'taste',
  'bun',
  'pork',
  'gyoza',
  'filling',
  'flavour',
  'reason',
  'gave',
  'review',
  'stuffed',
  'green',
  'chile',
  'pancakes',
  'reasonable',
  'filling',
  'flavour',
  'daughter',
  'mentioned',
  'generally',
  'liked',
  'itsu',
  'products',
  'gave',
  'rest',
  'freezer',
  'day',
  'told',
  'bao_buns',
  'ridiculously',
  'small',
  'filling',
  'unusual',
  'factory',
  'error',
  'company',
  'cutting',
  'ingredients',
  'rip',
  'customer'],
 ['food_okay',
  'pretty_good',
  'good',
  'overpriced',
  'app',
  'didn_work',
  'told',
  'restaurant',
  'manager',
  'way',
  'add',
  'credits',
  'later',
  'going',
  'launch',
  'loyalty',
  'scheme',
  'right',
  'anti',
  'loyalty',
  'scheme'],
 ['love',
  'going',
  'itsu',
  'point',
  'work',
  'lunch',
  'breaks',
  'recently',
  'ordering',
  'avocado',
  'sushi',
  'salmon',
  'set',
  'noticed',
  'pea',
  'sized',
  'dot',
  'wasabi',
  'tucked',
  'underneath',
  'sushi',
  'salmon',
  'tastes',
  'extremely',
  'unpleasant',
  'option',
  'like',
  'sushi',
  'restaurants',
  'wasabi',
  'inside',
  'sushi',
  'doesn',
  'option',
  'avocado',
  'salmon',
  'sushi',
  'wasabi',
  'inside',
  'roll',
  'disappointed'],
 ['price',
  'sushi',
  'getting',
  'tired',
  'endless',
  'undercooked',
  'slightly',
  'crunchy',
  'wet',
  'sushi_rice',
  'normal',
  'mirin',
  'moisture',
  'wet',
  'soggy',
  'want',
  'customers',
  'need',
  'basic',
  'ingredient',
  'correctly',
  'prepared',
  'makes',
  'feel',
  'ill',
  'need',
  'find',
  'way',
  'disposable',
  'plastic',
  'losing',
  'eat',
  'anymore',
  'hanover',
  'square',
  'branch'],
 ['itsu',
  'stansted',
  'airport',
  'tried',
  'pay_cash',
  'found',
  'itsu',
  'cashless',
  'mild',
  'annoyance',
  'live',
  'wasn',
  'okay',
  'cash',
  'register',
  'display',
  'said',
  'card',
  'preferred',
  'pointed',
  'somewhat',
  'obnoxious',
  'itsu',
  'employee',
  'pointed',
  'tiny',
  'little',
  'label',
  'said',
  'card',
  'card_machine',
  'going',
  'cashless',
  'clear',
  'customers',
  'choice',
  'asked',
  'pay',
  'likes',
  'told',
  'cash',
  'worthless',
  'oh',
  'sushi_rice',
  'undercooked',
  'occasions'],
 ['poor_experience',
  'new',
  'reading',
  'gate',
  'location',
  'food',
  'cooked',
  'dumplings',
  'rubbery',
  'cold',
  'centre',
  'service',
  'glum',
  'faces',
  'second',
  'visit',
  'row',
  'staff',
  'slamming',
  'self',
  'surface',
  'bin',
  'doors',
  'emptied',
  'shame',
  'high_hopes',
  'table',
  'agreed',
  'food',
  'prepared',
  'priced',
  'sure',
  'going',
  'hear',
  'improved',
  'let',
  'hope',
  'teething',
  'problems',
  'new',
  'branch',
  'reading',
  'reviews',
  'wonder',
  'itsu',
  'wider',
  'issues',
  'network'],
 ['sunday',
  'normally',
  'reading',
  'town',
  'end',
  'having',
  'favourite',
  'itsu',
  'coconut',
  'soup',
  'consist',
  'rice',
  'greens',
  'juicy',
  'bits',
  'chicken',
  'normally',
  'bream',
  'tasteful',
  'coconut',
  'flavoured',
  'soup',
  'visited',
  'today',
  'ordered',
  'favourite',
  'disappointed',
  'water',
  'possibly',
  'counted',
  'rice',
  'grains',
  'normally',
  'staple',
  'soup',
  'bits',
  'chicken',
  'bits',
  'greens',
  'wonder',
  'significantly',
  'reduced',
  'paid',
  'liquid',
  'little',
  'content',
  'disappointed',
  'customer'],
 ['rude',
  'staff',
  'bristol',
  'temple',
  'meads',
  'cutlery',
  'eating',
  'food',
  'chopsticks',
  'use',
  'toilet',
  'tissue',
  'loos',
  'supposed',
  'checked',
  'according',
  'chart',
  'door',
  'dreadful'],
 ['generally',
  'love',
  'itsu',
  'food',
  'peckish',
  'seek',
  'itsu',
  'similar',
  'food',
  'vendor',
  'stars',
  'butmy',
  'local',
  'itsu',
  'southwark',
  'st',
  'se',
  'months',
  'served',
  'smaller',
  'smaller',
  'amounts',
  'food',
  'thai',
  'chicken',
  'rice',

absolutely_love, highly_recommend, sont identifiés : Nous permettra de facilité la tâche lors de l'analyse de sentimenet / clustering des reviews.

In [321]:
"""
import sys
!{sys.executable} -m pip install spacy
!{sys.executable} -m spacy download en_core_web_sm
"""

'\nimport sys\n!{sys.executable} -m pip install spacy\n!{sys.executable} -m spacy download en_core_web_sm\n'

## Lemmatization & Stemming

run, running, runnable sont plusieurs mots qui ne devraient être compter que comme un seul lors de la création de Topic. 

Le Stemming est une méthode qui permet de couper les mots à leur racine de manière assez brutale (studies => studi) et peut apporter un manque de précision.  

La Lemmatization nous permet de s'approprier les règles grammaticales des mots afin de mieux les regrouper (running => run, better => good). Nous obtiendrons une fonction de comptage des mots plus précise avec cette méthode.  

La librairie Spacy nous aide encore une fois ici à appliquer cette méthode.

In [362]:
print(texts[0])

['big', 'guy', 'moses', 'works', 'itsu', 'gatwick', 'airport', 'kind', 'gentle', 'welcoming', 'journey', 'better', 'putting', 'smile', 'thanks', 'moses', 'continue', 'shine', 'light']

In [ ]:
def lemmatize_texts(texts, allowed_postags, spacy_model=None):

    if not spacy_model:
        spacy_model = spacy.load("en_core_web_sm")

    texts = [
        " ".join(doc) if isinstance(doc, list) else str(doc)
        for doc in texts
    ]

    docs = spacy_model.pipe(texts)

    return [
        [t.lemma_ for t in doc if t.pos_ in allowed_postags]
        for doc in docs
    ]

In [376]:
# Nous choissons de conserver les noms communs, noms propres, les verbes, adjectifs, adverbes ainsi que les termes non reconnus et spéciaux avec 'X'
l_texts = lemmatize_texts(texts_spacy,
                allowed_postags=['NOUN', 'ADJ', 'VERB', 'ADV', 'X', 'PROPN'])

In [382]:
count = compute_word_occurence(l_texts)

In [383]:
count.head(50)

                Word  Count
0              order   2314
1               food   2008
2               good   1372
3               time   1150
4               meal   1094
5           delivery    966
6              great    866
7                 go    825
8            service    688
9                box    682
10             staff    666
11            arrive    611
12               day    610
13              come    595
14               try    565
15              tell    517
16             drink    478
17               say    474
18           receive    473
19              item    473
20               eat    471
21           company    467
22               get    458
23               ask    453
24              find    449
25              week    448
26           product    435
27              need    433
28             thank    427
29             visit    408
30            lovely    408
31             taste    407
32             place    405
33           deliver    404
34        restaurant    400
35               buy    400
36        experience    398
37              look    395
38             leave    395
39              give    392
40  customer_service    387
41              nice    383
42             email    373
43               pay    372
44             table    372
45             price    371
46             think    365
47              wait    359
48              take    358
49              want    352

## Observations 

Nous observons maintenant que nos mots se concentrent bien sur des sujets cohérents avec notre thème "Restaurant & Bars" après la mise en place de notre pipeline de traitement de langage.  

Notre comptage de mot ne contient plus de stopwords, de double occurence et possède même des bigrams (customer_service) qui nous seront utiles pour nos prochaines analyses.

In [387]:
l_texts

[['big',
  'guy',
  'moses',
  'work',
  'itsu',
  'gatwick',
  'airport',
  'kind',
  'gentle',
  'welcoming',
  'journey',
  'well',
  'put',
  'smile',
  'thank',
  'moses',
  'continue',
  'shine',
  'light'],
 ['great_experience',
  'itsu',
  'thank',
  'hospitality',
  'moses',
  'gatwick',
  'airport',
  'south',
  'terminal'],
 ['itsu',
  'virgin',
  'enjoy',
  'lovely',
  'time',
  'experience',
  'itsu',
  'liverpool',
  'street',
  'staff',
  'exceptionally',
  'good',
  'helping',
  'navigate',
  'way',
  'ordering_process',
  'food',
  'hot',
  'tasty',
  'efficiently',
  'produce',
  'certainly',
  'try',
  'itsu'],
 ['itsu',
  'brunswick',
  'centre',
  'camden',
  'extremely',
  'nice',
  'sushi',
  'place',
  'staff_helpful',
  'especially',
  'ornella',
  'wojciech',
  'teach',
  'operate',
  'technology',
  'scan',
  'app',
  'claim',
  'butterfly',
  'ease',
  'teach',
  'access',
  'nhs',
  'discount',
  'thank',
  'goodness',
  'lovely',
  'staff',
  'enjoy',
  'job',
  'customer',
  'feel',
  'special'],
 ['itsu', 'read', 'gate', 'clean', 'restaurant', 'food', 'quick', 'great'],
 ['year_old',
  'son',
  'love',
  'restaurant',
  'chain',
  'order',
  'rice',
  'box',
  'absolutely_love',
  'normally',
  'complain',
  'eat',
  'vegetable',
  'way',
  'cook',
  'present',
  'mean',
  'happy',
  'eat',
  'veg',
  'decor',
  'beautiful'],
 ['eat',
  'itsu',
  'restaurant',
  'brunswick',
  'centre',
  'naast',
  'de',
  'excellent',
  'food',
  'service',
  'extra',
  'special',
  'smile',
  'genuine',
  'interest',
  'tourist',
  'visit',
  'time',
  'quick_efficient',
  'friendly'],
 ['lovely', 'food', 'highly_recommend'],
 ['itsu',
  'great',
  'menu',
  'fair',
  'price',
  'sushi',
  'phenomenal',
  'fresh',
  'love',
  'healthy',
  'option',
  'fast_food',
  'chain',
  'restaurant',
  'atmosphere',
  'dine',
  'great',
  'criticism',
  'include',
  'mini',
  'soy_sauce',
  'bottle',
  'sushi',
  'pack',
  'wasteful',
  'think',
  'instead',
  'option',
  'mini',
  'bottle',
  'want',
  'packaging',
  'great',
  'apart',
  'small',
  'criticism',
  'perfect',
  'absolutely_love',
  'app',
  'loyalty',
  'scheme',
  'definitely_recommend',
  'amazing',
  'restaurant'],
 ['visit',
  'brixton',
  'branch',
  'opening',
  'year_ago',
  'enjoy',
  'convenience',
  'grab',
  'hot',
  'meal',
  'min',
  'office',
  'especially',
  'love',
  'poach',
  'egg',
  'add',
  'dish',
  'order',
  'tend',
  'highly_recommend',
  'fancy',
  'asian',
  'inspire',
  'eat',
  'takeaway',
  'thing',
  'bear',
  'mind',
  'cashless',
  'eatery',
  'old',
  'schooler',
  'whip',
  'card'],
 ['morning',
  'visit',
  'itsu',
  'euston',
  'station',
  'issue',
  'card_machine',
  'transaction',
  'guess',
  'get',
  'lunch',
  'free',
  'touch',
  'thank',
  'itsu',
  'hope',
  'issue',
  'solve',
  'appreciate',
  'kindness',
  'thank'],
 ['work',
  'bank',
  'office',
  'lunch',
  'itsu',
  'cheapside',
  'people',
  'office',
  'collect',
  'order',
  'work',
  'colleague',
  'lunch',
  'list',
  'renata',
  'shop',
  'manager',
  'amazing',
  'quick',
  'organize',
  'count',
  'smile',
  'customer',
  'feel',
  'welcome',
  'experience',
  'itsu',
  'absolutely',
  'positive',
  'know',
  'itsu',
  'branch',
  'know',
  'business',
  'renata',
  'success',
  'guarantee',
  'dani'],
 ['struggle',
  'redeem',
  'voucher',
  'approach',
  'manager_came',
  'help',
  'regular_custom',
  'nhg',
  'branch',
  'woman',
  'fantastic',
  'smile',
  'cheerful',
  'extremely_helpful',
  'promote',
  'new',
  'product',
  'help',
  'customer',
  'efficient'],
 ['manager',
  'silverio',
  'victoria',
  'station',
  'itsu',
  'kind',
  'thoughtful',
  'day',
  'feel',
  'unwell',
  'offer',
  'fabulous',
  'chicken',
  'noodle',
  'soup',
  'head',
  'soon',
  'day',
  'moment',
  'gesture',
  'kindness',
  'thank'],
 ['find',
  'itsu',
  'king',
  'road',
  'chelsea',
  'welcome',
  'tasty',
  'food',
  'reasonable_price',
  'favourite',
  'thai',
  'noodle',
  'price',
  'pound',
  'find',
  'scrumptious',
  'dish',
  'price',
  'handicap',
  'mobility',
  'scooter',
  'staff',
  'manager',
  'adrian',
  'gracious',
  'help',
  'give',
  'table',
  'service',
  'object',
  'scooter',
  'way',
  'pleasure',
  'itsu',
  'king',
  'rd',
  'chelsea',
  'visit',
  'february',
  'lucky',
  'itsu',
  'locally'],
 ['brother',
  'visit',
  'itsu',
  'victoria',
  'station',
  'yesterday',
  'absolutely',
  'starve',
  'exhausted',
  'grab',
  'gyoza',
  'mochi',
  'serve',
  'priya',
  'friendly',
  'smile',
  'extremely_helpful',
  'give',
  'box',
  'bao_buns',
  'free',
  'end',
  'day',
  'lovely',
  'extra',
  'end',
  'long',
  'day',
  'thank',
  'priya'],
 ['love',
  'food',
  'tasty',
  'present',
  'decent',
  'portion',
  'packaging',
  'nicely',
  'order',
  'food',
  'delivery_service',
  'leave',
  'food',
  'vulnerable',
  'tampering',
  'mention',
  'arrive',
  'cold',
  'itsu',
  'packaging',
  'food',
  'warm',
  'seal',
  'food',
  'prevent',
  'spill',
  'tamper'],
 ['itsu',
  'victoria',
  'station',
  'fabulous',
  'staff',
  'great',
  'manager',
  'go',
  'cater',
  'tolerence',
  'visit',
  'welcome',
  'huge',
  'smile',
  'cheerful',
  'attitude',
  'manager',
  'visit',
  'int',
  'area',
  'thank'],
 ['visit',
  'itsu',
  'wembley',
  'park',
  'today',
  'surprise',
  'friendly_staff',
  'particularly',
  'gabriel',
  'addition',
  'great_service',
  'food',
  'good',
  'healthy',
  'reasonably_price',
  'fault',
  'overall',
  'visit',
  'day'],
 ['clean',
  'tidy',
  'fast',
  'friendly_service',
  'plenty',
  'condiment',
  'cutlery',
  'option',
  'napkin',
  'available',
  'feel',
  'rush',
  'table',
  'finish'],
 ['good_service', 'nice', 'people', 'highly_recommend'],
 ['early',
  'adopter',
  've',
  'itsu',
  'start',
  'fan',
  'salmon',
  'go',
  'iffy',
  'phase',
  'month',
  'crunchy',
  'texture',
  'good',
  'couple',
  'years_ago',
  'good',
  'difference',
  'outlet',
  'good',
  'bad',
  'subjective',
  'itsu',
  'social_media',
  'person',
  'don',
  'comment',
  'issue',
  'address',
  'don_need',
  'ego',
  'stroke',
  'disrespect',
  'intend'],
 ['disappoint',
  'buy',
  'sushi',
  'realise',
  'wasabi',
  'unfortunately',
  'waste_money',
  'simply',
  'enquire',
  'online',
  'possible',
  'future',
  'remove',
  'sandra',
  'go',
  'kindly',
  'send',
  'voucher',
  'impress',
  'look_forward',
  'order',
  'sushi',
  'wasabi',
  'future'],
 ['buy',
  'lunch',
  'itsu',
  'fairly',
  'regularly',
  'healthy',
  'nutritious',
  'minimal',
  'fuss',
  'shop',
  'chancery',
  'lane',
  'london',
  'small',
  'friendly',
  'busy',
  'appear',
  'wasabi',
  'reason',
  'review',
  'doesn',
  'star',
  'recently',
  'stop',
  'sell',
  'rice',
  'veggie',
  'dumpling',
  'eat',
  'miso',
  'explore',
  'option',
  'mean',
  've_trie',
  'food',
  'sell',
  'beat',
  'ease',
  'taste',
  'rice',
  'dumpling',
  'bring'],
 ['previously',
  'give',
  'itsu',
  'low',
  'rating',
  'visit',
  'couple_time',
  'improve',
  'vastly',
  'price',
  'expensive',
  'customer_service',
  'well',
  'thank'],
 ['itsu',
  'great',
  'sushi',
  'price',
  'eat',
  'budget',
  'price',
  'sushi',
  'lunch',
  'break',
  'quick',
  'fresh',
  'variety',
  'good',
  'eating',
  'facility',
  'good',
  'well',
  'sushi',
  'high',
  'end',
  'restaurant',
  'cost',
  'include',
  'expensive',
  'drink',
  'personal',
  'server',
  'end',
  'sushi',
  'chef',
  'quick',
  'sushi',
  'itsu',
  'decent',
  'good_value'],
 ['regular',
  'lunch',
  'chicken',
  'teryaki',
  'bowl',
  'soho',
  'branch',
  'good',
  'tasty',
  'quick',
  'pleasant',
  'service'],
 ['good_service',
  'good',
  'food',
  'nice',
  'tasty',
  'healthy',
  'food',
  'option',
  'maybe',
  'rid',
  'sugary',
  'drink',
  'shelve',
  'small',
  'fish'],
 ['average', 'sushi', 'great', 'customer_experience', 'good', 'hurry'],
 ['good', 'queue', 'food', 'ready'],
 ['food',
  'dish',
  'jasmine',
  'tea',
  'consider',
  'good_value_money',
  'couple',
  'location',
  'excessively',
  'loud',
  'music',
  'play',
  'turn',
  'volume'],
 ['open',
  'exeter',
  'branch',
  'itsu',
  'times',
  'day',
  'bullet',
  'point',
  'simplify',
  'thought',
  'fit',
  'premise',
  'beautifully',
  'food',
  'beautiful',
  'exactly',
  'describe',
  'menu',
  'maybe',
  'train',
  'lack',
  'experience',
  'accept',
  'cash',
  'legal',
  'tender',
  'company',
  'ban',
  'particular',
  'urk',
  'display',
  'opening',
  'time',
  'shop',
  'funny',
  'closing',
  'time',
  'pm',
  'mon',
  'thursday',
  'pm',
  'friday',
  'onwards',
  'miss',
  'customer',
  'city',
  'little',
  'way',
  'takeaway',
  'healthy',
  'alternative',
  'review',
  'adjust',
  'thing',
  'sure',
  'improve',
  'cash',
  'ban',
  'leave',
  'recommend',
  'time',
  'strong',
  'advocate',
  'use',
  'cash'],
 ['great',
  'sushi',
  'good_service',
  'consistent',
  'feed',
  'ridiculous',
  'attitude',
  'request',
  'ginger',
  'box',
  'sushi',
  'vendor',
  'place',
  'ginger',
  'offering',
  'itsu',
  'stop',
  'ask',
  'little',
  'ginger',
  'counter',
  'assure',
  'write',
  'itsu',
  'policy',
  'provide',
  'packet',
  'ginger',
  'free_charge',
  'boxed',
  'item',
  'request',
  'realise',
  'time',
  'merry',
  'dance',
  'add',
  'ridiculously',
  'trivial',
  'sachet',
  'money',
  'inconsistency',
  'childishness',
  'frustration'],
 ['bad',
  'place',
  'work',
  'job',
  'security',
  'bad',
  'hour',
  'work',
  'reliability',
  'hour',
  'week',
  'depend',
  'staff',
  'management',
  'usually',
  'god',
  'awful',
  'people',
  'promote',
  'nepotism',
  'basis',
  'hr',
  'alright',
  'ceo',
  'abandon',
  'care',
  'employee',
  'leave',
  'covid',
  'pret',
  'manger',
  'fire',
  'staff'],
 ['buy',
  'itsu',
  'crispy',
  'seaweed',
  'thin',
  'supermarket',
  'husband',
  'absolutely_love',
  'don_want',
  'buy',
  'plastic_package',
  'horrendous',
  'individual',
  'packet',
  'contain',
  'plastic',
  'holder',
  'wrap',
  'plastic',
  'wrap',
  'outer',
  'layer',
  'plastic',
  'keep',
  'individual',
  'packet',
  'contain',
  'small',
  'plastic',
  'packet',
  'substance',
  'stop',
  'product',
  'spoil',
  'appreciate',
  'product',
  'delicate',
  'seriously',
  'environmentally',
  'friendly',
  'way',
  'deliver',
  'product',
  'customer',
  'bear',
  'throw',
  'packet',
  'packet',
  'bin',
  'address',
  'issue'],
 ['get',
  'lloyds',
  'bank',
  'world',
  'elite',
  'card',
  'invite',
  'sign',
  'itsu',
  'reward',
  'partner',
  'decide',
  'itsu',
  'go',
  'bath',
  'store',
  'gyoza',
  'firstly',
  'couldn',
  'use_app',
  'keep',
  'say',
  'wouldn',
  'scan',
  'couldn',
  'work',
  'order',
  'go',
  'counter',
  'say',
  'able',
  'add',
  'butterfly',
  'account',
  'feel',
  'weird',
  'tell',
  'couldn',
  'need',
  'spend',
  'fiver',
  'explain',
  'tell',
  'website',
  'help',
  'nope',
  'help',
  'whatsoever',
  'option',
  'able',
  'ask',
  'general',
  'question',
  'help',
  'decide',
  'message',
  'marketing',
  'upload',
  'photo',
  'food',
  'receipt',
  'nope',
  'crash',
  'say',
  'issue',
  'great_service'],
 ['look',
  'menu',
  'online',
  'look',
  'delicious',
  'present',
  'bowl',
  'day',
  'order',
  'show',
  'dish',
  'bowl',
  'ordering',
  'give',
  'cardboard',
  'tub',
  'think',
  'watery',
  'slop',
  'flavour',
  'water',
  'overprice'],
 ['special',
  'annoy',
  'order',
  'english',
  'breakfast',
  'tea',
  'london',
  'find',
  'provide',
  'milk',
  'sort',
  'simply',
  'sloppy',
  'drink',
  'black',
  'disgusting'],
 ['special',
  'honest',
  'don',
  'support',
  'company',
  'charge',
  'sit',
  'eat',
  'customer',
  'pay',
  'tax',
  'know',
  'lot',
  'company',
  'rule',
  'apparently',
  'apply',
  'hot',
  'food',
  'tell',
  'item',
  'apply',
  'sushi',
  'pretty_good',
  'fresh',
  'sure',
  'ingredient',
  'particularly',
  'sauce',
  'company',
  'sell',
  'sort',
  'food',
  'use',
  'msg',
  'particularly',
  'nasty',
  'ingredient',
  'ask',
  'staff',
  'tell',
  'know',
  'msg',
  'look',
  'web_site',
  'yo_sushi',
  'informed',
  'check',
  'tell',
  'product',
  'soup',
  'contain',
  'surprised',
  'lack',
  'training',
  'itsu',
  'particularly',
  'ordeal',
  'pret',
  'people',
  'allergie',
  'consequence',
  'customer',
  'ask',
  'allergy',
  'sulfite',
  'thing',
  'allergy',
  'wagamama',
  'sauce',
  'preservative',
  'summarise',
  'research',
  'use',
  'particularly',
  'soup',
  'sauce',
  'surprised',
  'place',
  'eat',
  'regularly',
  'cause',
  'problem',
  'long',
  'term',
  'ingredient',
  'good',
  'don',
  'mislead',
  'fact',
  'thing',
  'sushi',
  'consider',
  'good',
  'case',
  'look',
  'add',
  'dish',
  'go',
  'update',
  'review',
  'soon',
  'update',
  'concern',
  'msg',
  'sulfite'],
 ['question',
  'different',
  'price',
  'vegetable',
  'dumpling',
  'hot',
  'price',
  'cold',
  'makes_sense'],
 ['thi',
  'dirty',
  'don',
  'clean',
  'sanitise',
  'counter',
  'top',
  'tray',
  'use',
  'eat',
  'food',
  'hover',
  'staff_rude',
  'overbear',
  'suchi',
  'fall',
  'apart',
  'pick',
  'chop',
  'stick',
  'dumpling',
  'fall',
  'apart',
  'make',
  'soup',
  'uninvite',
  'put',
  'eat',
  'honest',
  'thi',
  'toilet',
  'aren',
  'clean',
  'man',
  'woman',
  'share',
  'toilet',
  'odd',
  'putting'],
 ['get',
  'chicken_teriyaki',
  'rice_bowl',
  'food',
  'recent',
  'time',
  'get',
  'chicken_teriyaki',
  'rice_bowl',
  'give',
  'food_poisoning',
  'remember',
  'look',
  'chicken',
  'thinking',
  'look',
  'funny',
  'ignore',
  'eat',
  'worst',
  'food_poisone',
  'hot',
  'hot',
  'fever',
  'chill'],
 ['go',
  'itsu',
  'eat',
  'beautiful',
  'fosse',
  'park',
  'leicester',
  'week',
  'time',
  'customer_service',
  'welcome',
  'return',
  'smile',
  'welcome',
  'begrudgingly',
  'want',
  'spend_money',
  'opt',
  'salmon',
  'salad',
  'box',
  'promotional',
  'offer',
  'look',
  'good',
  'similar',
  'photo',
  'unfortunately',
  'stingy',
  'small',
  'piece',
  'salmon',
  'cheap',
  'brown',
  'rice',
  'bean',
  'stuff',
  'taste',
  'bland',
  'flavour',
  'dip',
  'come',
  'boring',
  'definitely',
  'lack',
  'flavour',
  'wouldn',
  'come',
  'greggs',
  'sandwich',
  'door',
  'flavour'],
 ['feel_like',
  'menu',
  'bore',
  'cheap',
  'term',
  'quality',
  'tasty',
  'lot',
  'ingredient',
  'hard',
  'digest',
  'combine',
  'uncooked',
  'cabbage',
  'kale',
  'onion',
  'etc',
  'dish',
  'design',
  'menu',
  'feel',
  'bloated',
  'time',
  'itsu',
  'get',
  'lot',
  'expensive',
  'menu',
  'feel',
  'tired',
  'app',
  'finally_got',
  'bit',
  'well',
  'buggy',
  'interface',
  'freebie',
  'intuitive',
  'need',
  'time',
  'trouble',
  'shoot',
  'favourite',
  'lunch',
  'spot',
  'forgot',
  'bring',
  'lunch',
  'close',
  'office'],
 ['try',
  'itsu',
  'product',
  'supermarket',
  'time',
  'teriyaki',
  'chicken',
  'bao_bun',
  'mm',
  'filling',
  'taste',
  'bun',
  'pork',
  'gyoza',
  'fill',
  'flavour',
  'reason',
  'give',
  'review',
  'stuff',
  'green',
  'chile',
  'pancake',
  'reasonable',
  'fill',
  'flavour',
  'daughter',
  'mention',
  'generally',
  'like',
  'itsu',
  'product',
  'give',
  'rest',
  'freezer',
  'day',
  'tell',
  'bao_bun',
  'ridiculously',
  'small',
  'fill',
  'unusual',
  'factory',
  'error',
  'company',
  'cut',
  'ingredient',
  'rip',
  'customer'],
 ['pretty_good',
  'good',
  'overprice',
  'app',
  'didn_work',
  'tell',
  'restaurant',
  'manager',
  'way',
  'add',
  'credit',
  'later',
  'go',
  'launch',
  'loyalty',
  'scheme',
  'right',
  'anti',
  'loyalty',
  'scheme'],
 ['love',
  'go',
  'itsu',
  'point',
  'work',
  'lunch',
  'break',
  'recently',
  'order',
  'avocado',
  'sushi',
  'salmon',
  'set',
  'notice',
  'pea',
  'size',
  'dot',
  'wasabi',
  'tuck',
  'sushi',
  'salmon',
  'taste',
  'extremely',
  'unpleasant',
  'option',
  'sushi',
  'restaurant',
  'wasabi',
  'sushi',
  'doesn',
  'option',
  'avocado',
  'salmon',
  'sushi',
  'wasabi',
  'roll',
  'disappoint'],
 ['price',
  'sushi',
  'get',
  'tired',
  'endless',
  'undercooked',
  'slightly',
  'crunchy',
  'wet',
  'sushi_rice',
  'normal',
  'mirin',
  'moisture',
  'wet',
  'soggy',
  'want',
  'customer',
  'need',
  'basic',
  'ingredient',
  'correctly',
  'prepared',
  'make',
  'feel',
  'ill',
  'need',
  'find',
  'way',
  'disposable',
  'plastic',
  'losing',
  'eat',
  'anymore',
  'hanover',
  'square',
  'branch'],
 ['itsu',
  'stansted',
  'airport',
  'try',
  'pay_cash',
  'find',
  'itsu',
  'cashless',
  'mild',
  'annoyance',
  'live',
  'wasn',
  'okay',
  'cash',
  'register',
  'display',
  'say',
  'card',
  'preferred',
  'point',
  'somewhat',
  'obnoxious',
  'itsu',
  'employee',
  'point',
  'tiny',
  'little',
  'label',
  'say',
  'card',
  'card_machine',
  'go',
  'cashless',
  'clear',
  'customer',
  'choice',
  'ask',
  'pay',
  'like',
  'tell',
  'cash',
  'worthless',
  'sushi_rice',
  'undercooked',
  'occasion'],
 ['poor_experience',
  'new',
  'reading',
  'gate',
  'location',
  'food',
  'cook',
  'dumpling',
  'rubbery',
  'cold',
  'centre',
  'service',
  'glum',
  'face',
  'second',
  'visit',
  'row',
  'staff',
  'slam',
  'self',
  'surface',
  'bin',
  'door',
  'empty',
  'shame',
  'high_hope',
  'table',
  'agree',
  'food',
  'prepare',
  'price',
  'sure',
  'go',
  'hear',
  'improve',
  'let',
  'hope',
  'teethe',
  'problem',
  'new',
  'branch',
  'read',
  'review',
  'wonder',
  'itsu',
  'wide',
  'issue',
  'network'],
 ['sunday',
  'normally',
  'read',
  'town',
  'end',
  'have',
  'favourite',
  'itsu',
  'coconut',
  'soup',
  'consist',
  'rice',
  'greens',
  'juicy',
  'bit',
  'chicken',
  'normally',
  'bream',
  'tasteful',
  'coconut',
  'flavour',
  'soup',
  'visit',
  'today',
  'order',
  'favourite',
  'disappointed',
  'water',
  'possibly',
  'count',
  'rice',
  'grain',
  'normally',
  'staple',
  'soup',
  'bit',
  'chicken',
  'bit',
  'green',
  'wonder',
  'significantly',
  'reduce',
  'pay',
  'liquid',
  'little',
  'content',
  'disappoint',
  'customer'],
 ['rude',
  'staff',
  'bristol',
  'temple',
  'mead',
  'cutlery',
  'eat',
  'food',
  'chopstick',
  'use',
  'toilet',
  'tissue',
  'loo',
  'check',
  'accord',
  'chart',
  'door',
  'dreadful'],
 ['generally',
  'love',
  'itsu',
  'food',
  'peckish',
  'seek',
  'itsu',
  'similar',
  'food',
  'vendor',
  'star',
  'butmy',
  'local',
  'itsu',
  'southwark',
  'st',
  'se',
  'month',
  'serve',
  'small',
  'small',
  'amount',
  'food',
  'thai',
  'chicken',
  'rice',
  'bowl',
  'moan',
  'shortage',
  'chicken',
  'usually',
  'rice',
  'miss',
  'find',
  'disappoint',
  'give',
  'cost',
  'dish',
  'cheap',
  'ingredient',
  'include',
  'ask',
  'manager',
  'change',
  'portion_size',
  'dish',
  'tell',
  'hadn',
  'give',
  'rice_bowl',
  'packet',
  'good',
  'have',
  'large',
  'packet',
  'environmentally',
  'wasteful',
  'mislead',
  'customer',
  'come',
  'itsu',
  'sort',
  'use',
  'packaging',
  'include',
  'food'],
 ['go',
  'itsu',
  'outlet',
  'lunch',
  'self',
  'order',
  'kiosk',
  'chicken_teriyaki',
  'rice_bowl',
  'extra',
  'chicken',
  'looked_like',
  'big',
  'ceramic',
  'bowl',
  'ton',
  'rice',
  'get',
  'order',
  'surprise',
  'tiny',
  'size',
  'portion',
  'small',
  'tub',
  'ben',
  'jerry',
  'cost',
  'disappointing',
  'decent',
  'food',
  'return'],
 ['itsu',
  'brighton',
  'ok',
  'obviously',
  'cheap',
  'cheerful',
  'chain',
  'comfortable',
  'food',
  'lukewarm',
  'main',
  'issue',
  'refuse',
  'cash',
  'payment',
  'lazy',
  'way',
  'company',
  'operate',
  'show',
  'concerned',
  'customer'],
 ['visit',
  'itsu',
  'read',
  'high_street',

On ajoute notre colonne de phrases lemmatizées à notre DataFrame.

In [389]:
df_resto["l_texts"] = l_texts

C:\Users\Rudyl\AppData\Local\Temp/ipykernel_19568/3679679886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_resto["l_texts"] = l_texts

In [390]:
df_resto

,category,company,description,title,review,stars,l_texts
49908,Restaurants & Bars,itsu.com,"Delicious, healthy, Asian inspired food, fresh...",Big up to my guy Moses who works in the…,Big up to my guy Moses who works in the itsu i...,5,"[big, guy, moses, work, itsu, gatwick, airport..."
49909,Restaurants & Bars,itsu.com,"Delicious, healthy, Asian inspired food, fresh...",Great experience at itsu thanks to…,Great experience at itsu thanks to hospitality...,5,"[great_experience, itsu, thank, hospitality, m..."
49910,Restaurants & Bars,itsu.com,"Delicious, healthy, Asian inspired food, fresh...",As Itsu virgins we enjoyed a lovely…,As Itsu virgins we enjoyed a lovely first time...,5,"[itsu, virgin, enjoy, lovely, time, experience..."
49911,Restaurants & Bars,itsu.com,"Delicious, healthy, Asian inspired food, fresh...",ITSU at Brunswick Centre: three cheers for the...,"ITSU at Brunswick Centre, Camden is an extreme...",5,"[itsu, brunswick, centre, camden, extremely, n..."
49912,Restaurants & Bars,itsu.com,"Delicious, healthy, Asian inspired food, fresh...",Itsu Reading Gate is Great,At Itsu Reading Gate and clean restaurant and ...,5,"[itsu, read, gate, clean, restaurant, food, qu..."
...,...,...,...,...,...,...,...
112775,Restaurants & Bars,littleleeds.co.uk,A modern and chic play café for grown ups to e...,Not bad!,We loved the idea and our boy enjoyed it!!! No...,3,"[love, idea, boy, enjoy, keen, birthday_party,..."
112776,Restaurants & Bars,littleleeds.co.uk,A modern and chic play café for grown ups to e...,Disappointing,I really want to like this place but I echo ot...,3,"[want, place, echo, people, feeling, people, a..."
112777,Restaurants & Bars,littleleeds.co.uk,A modern and chic play café for grown ups to e...,Really lovely little place however as…,Really lovely little place however as you ente...,3,"[lovely, little, place, enter, array, sugary, ..."
112778,Restaurants & Bars,littleleeds.co.uk,A modern and chic play café for grown ups to e...,Disappointed,This was a disappointing trip as it was very s...,3,"[disappointing, trip, small, venue, hardly, sp..."
112779,Restaurants & Bars,littleleeds.co.uk,A modern and chic play café for grown ups to e...,Disappointing,I’ve been twice and I’m sorry to say that I’m ...,3,"[ve, twice, sorry, disappointed, place, open, ..."

Afin d'analyser et d'affectuer des modélisations plus approfondies, la colonnes l_texts nous sera très utiles.

In [ ]:
pd.to_csv(